// web/src/views/ChatView.tsx
import { Paperclip, Send, Square, X } from "lucide-react";
import { type DragEvent, type KeyboardEvent, useEffect, useRef, useState } from "react";
import { IoMark } from "@/components/IoMark";
import { MessageBubble } from "@/components/ui/MessageBubble";
import {
  fileToMessageAttachment,
  formatAttachmentSize,
  type MessageAttachment,
  validateAttachmentSizes,
} from "@/lib/attachments";
import { useChatStore } from "@/stores/chat";

export default function ChatView() {
  const messages = useChatStore((s) => s.messages);
  const isStreaming = useChatStore((s) => s.isStreaming);
  const sendMessage = useChatStore((s) => s.sendMessage);
  const stopStreaming = useChatStore((s) => s.stopStreaming);

  const [input, setInput] = useState("");
  const [pendingAttachments, setPendingAttachments] = useState<MessageAttachment[]>([]);
  const [composerError, setComposerError] = useState("");
  const [isDragging, setIsDragging] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, []);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 160)}px`;
    }
  }, []);

  const handleSend = async () => {
    const trimmed = input.trim();
    if (!trimmed && pendingAttachments.length === 0) return;
    setInput("");
    setComposerError("");
    const attachments = [...pendingAttachments];
    setPendingAttachments([]);
    await sendMessage(trimmed, attachments);
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleFiles = async (files: FileList | File[]) => {
    const newAttachments: MessageAttachment[] = [];
    for (const file of Array.from(files)) {
      newAttachments.push(await fileToMessageAttachment(file));
    }
    const combined = [...pendingAttachments, ...newAttachments];
    const validated = validateAttachmentSizes(combined);
    if (!validated.ok) {
      setComposerError(validated.error);
      return;
    }
    setPendingAttachments(combined);
  };

  const handleDrop = (e: DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files.length) handleFiles(e.dataTransfer.files);
  };

  return (
    <div
      className="flex flex-col flex-1 min-h-0"
      onDragOver={(e) => {
        e.preventDefault();
        setIsDragging(true);
      }}
      onDragLeave={() => setIsDragging(false)}
      onDrop={handleDrop}
    >
      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-5 py-5 space-y-5">
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-center">
            <IoMark height={48} />
            <p className="text-zinc-600 font-mono text-sm">Start a conversation with IO</p>
          </div>
        )}
        {messages.map((msg) => (
          <div key={msg.id} className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}>
            <MessageBubble msg={msg} />
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>

      {/* Input area */}
      <div className="border-t border-white/[0.06] p-4 flex-shrink-0">
        {composerError && <div className="text-[11px] font-mono text-red-400 mb-2">{composerError}</div>}

        {pendingAttachments.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-2">
            {pendingAttachments.map((att, i) => (
              <div
                key={`${att.name}:${att.size}:${att.mimeType}`}
                className="flex items-center gap-2 bg-[#252525] border border-white/[0.08] rounded-xl px-3 py-1.5"
              >
                <span className="text-[10px] font-mono text-zinc-400 truncate max-w-[120px]">{att.name}</span>
                <span className="text-[9px] font-mono text-zinc-600">{formatAttachmentSize(att.size)}</span>
                <button
                  onClick={() => setPendingAttachments((p) => p.filter((_, idx) => idx !== i))}
                  className="text-zinc-600 hover:text-zinc-300 cursor-pointer"
                >
                  <X className="w-3 h-3" />
                </button>
              </div>
            ))}
          </div>
        )}

        <div
          className={`bg-[#1e1e1e] border rounded-2xl overflow-hidden transition-colors focus-within:border-[#66FCF1]/30 ${isDragging ? "border-[#66FCF1]/50" : "border-white/[0.08]"}`}
        >
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Message IO…"
            rows={1}
            className="w-full bg-transparent px-4 pt-3 pb-1 text-sm text-zinc-200 placeholder:text-zinc-700 resize-none focus:outline-none"
            style={{ minHeight: "42px", maxHeight: "160px", fontFamily: "Inter, sans-serif" }}
          />
          <div className="flex items-center justify-between px-3 pb-2.5">
            <button
              onClick={() => {
                const input = document.createElement("input");
                input.type = "file";
                input.multiple = true;
                input.onchange = () => {
                  if (input.files) handleFiles(input.files);
                };
                input.click();
              }}
              className="p-1.5 rounded-lg hover:bg-white/[0.05] text-zinc-700 hover:text-zinc-400 transition-colors cursor-pointer"
            >
              <Paperclip className="w-4 h-4" />
            </button>
            <div className="flex items-center gap-2">
              {isStreaming ? (
                <button
                  onClick={stopStreaming}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-[11px] font-mono text-zinc-300 transition-colors"
                >
                  <Square className="w-3 h-3" /> Stop
                </button>
              ) : (
                <button
                  onClick={handleSend}
                  disabled={!input.trim() && pendingAttachments.length === 0}
                  className="p-2 rounded-xl text-[#1F2833] disabled:opacity-30 disabled:cursor-not-allowed transition-opacity hover:opacity-90"
                  style={{ background: "var(--base-teal)" }}
                >
                  <Send className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>
        </div>
        <p className="text-center text-[11px] text-zinc-800 font-mono mt-2">
          IO may make mistakes. Verify important outputs.
        </p>
      </div>
    </div>
  );
}

// web/src/views/ChatView.vue
<script setup lang="ts">
import { computed, ref, nextTick, onMounted, watch } from "vue";
import { useChatStore } from "@/stores/chat";
import { Send, Square, Paperclip, X, Image as ImageIcon, FileText } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";
import LogoIcon from "@/components/LogoIcon.vue";
import {
  fileToMessageAttachment,
  formatAttachmentSize,
  isImageAttachment,
  MAX_ATTACHMENT_BYTES,
  MAX_TOTAL_ATTACHMENT_BYTES,
  toDataUrl,
  type MessageAttachment,
  validateAttachmentSizes,
} from "@/lib/attachments";

const chat = useChatStore();
const input = ref("");
const composerError = ref("");
const messagesContainer = ref<HTMLElement>();
const fileInput = ref<HTMLInputElement>();
const pendingAttachments = ref<MessageAttachment[]>([]);
const textareaRef = ref<HTMLTextAreaElement>();
const isDragging = ref(false);

const totalPendingAttachmentBytes = computed(() =>
  pendingAttachments.value.reduce((sum, attachment) => sum + attachment.size, 0)
);

const canSend = computed(
  () =>
    !chat.isStreaming &&
    (input.value.trim().length > 0 || pendingAttachments.value.length > 0)
);

async function queueAttachments(files: FileList | null): Promise<void> {
  if (!files || files.length === 0) return;

  composerError.value = "";
  const parsed: MessageAttachment[] = [];

  try {
    for (const file of Array.from(files)) {
      parsed.push(await fileToMessageAttachment(file));
    }
  } catch (err: any) {
    composerError.value = err?.message ?? "Unable to read one or more files.";
    return;
  }

  const next = [...pendingAttachments.value, ...parsed];
  const validation = validateAttachmentSizes(next);
  if (!validation.ok) {
    composerError.value = validation.error;
    return;
  }

  pendingAttachments.value = next;
  if (fileInput.value) fileInput.value.value = "";
}

function removeAttachment(index: number): void {
  pendingAttachments.value.splice(index, 1);
  composerError.value = "";
}

function openPicker(): void {
  fileInput.value?.click();
}

function handleFileInput(event: Event): void {
  const target = event.target as HTMLInputElement | null;
  void queueAttachments(target?.files ?? null);
}

async function send() {
  if (!canSend.value) return;

  const text = input.value.trim();
  const attachments = [...pendingAttachments.value];
  const prompt = text || "Please review the attached file(s).";

  input.value = "";
  pendingAttachments.value = [];
  composerError.value = "";

  await chat.sendMessage(prompt, attachments);
}

function scrollToBottom() {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
  }
}

function updateComposerHeight(): void {
  if (!textareaRef.value) return;
  textareaRef.value.style.height = "auto";
  textareaRef.value.style.height = `${Math.min(textareaRef.value.scrollHeight, 120)}px`;
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    send();
  }
}

function onDragOver(event: DragEvent): void {
  event.preventDefault();
  isDragging.value = true;
}

function onDragLeave(event: DragEvent): void {
  event.preventDefault();
  isDragging.value = false;
}

async function onDrop(event: DragEvent): Promise<void> {
  event.preventDefault();
  isDragging.value = false;
  await queueAttachments(event.dataTransfer?.files ?? null);
}

// Auto-scroll whenever messages change (new message, streaming content updates)
watch(
  () => chat.messages.map((m) => m.content),
  async () => {
    await nextTick();
    scrollToBottom();
  },
  { deep: true }
);

watch(
  () => chat.messages.length,
  async () => {
    await nextTick();
    scrollToBottom();
  }
);

watch(
  () => input.value,
  async () => {
    await nextTick();
    updateComposerHeight();
  }
);

onMounted(() => {
  updateComposerHeight();
  scrollToBottom();
});
</script>

<template>
  <div class="flex flex-col h-full">
    <!-- Messages -->
    <div ref="messagesContainer" class="flex-1 overflow-y-auto p-4 space-y-4">
      <div v-if="chat.messages.length === 0" class="flex items-center justify-center h-full">
        <div class="text-center text-muted-foreground">
          <LogoIcon :size="56" class="mx-auto mb-4" />
          <p class="text-lg font-medium">Welcome to IO</p>
          <p class="text-sm mt-1">Send a message to get started.</p>
        </div>
      </div>

      <div
        v-for="msg in chat.messages"
        :key="msg.id"
        class="flex"
        :class="msg.role === 'user' ? 'justify-end' : 'justify-start'"
      >
        <div
          class="max-w-[75%] rounded-lg px-4 py-2 text-sm"
          :class="
            msg.role === 'user'
              ? 'bg-primary text-primary-foreground'
              : 'bg-muted text-foreground'
          "
        >
          <div v-if="msg.attachments.length > 0" class="mb-2 space-y-2">
            <div
              v-for="(attachment, idx) in msg.attachments"
              :key="`${msg.id}-${idx}`"
              class="rounded border border-border/50 p-2 bg-background/70 text-foreground"
            >
              <img
                v-if="isImageAttachment(attachment)"
                :src="toDataUrl(attachment)"
                :alt="attachment.name"
                class="max-h-44 rounded mb-1 object-contain"
              />
              <div class="flex items-center gap-2 text-xs">
                <ImageIcon v-if="isImageAttachment(attachment)" class="w-3.5 h-3.5" />
                <FileText v-else class="w-3.5 h-3.5" />
                <span class="truncate">{{ attachment.name }}</span>
                <span class="opacity-70">{{ formatAttachmentSize(attachment.size) }}</span>
              </div>
            </div>
          </div>
          <MarkdownContent v-if="msg.content" :content="msg.content" :class="msg.role === 'user' ? 'prose-invert' : ''" />
          <span v-else-if="!msg.streaming" class="text-muted-foreground">...</span>
          <div
            v-if="msg.streaming"
            class="inline-block w-2 h-4 bg-current animate-pulse ml-1"
          ></div>
        </div>
      </div>
    </div>

    <!-- Input -->
    <div
      class="border-t border-border p-4"
      :class="isDragging ? 'bg-accent/40' : ''"
      @dragover="onDragOver"
      @dragleave="onDragLeave"
      @drop="onDrop"
    >
      <input
        ref="fileInput"
        type="file"
        multiple
        class="hidden"
        @change="handleFileInput"
      />

      <div v-if="pendingAttachments.length > 0" class="mb-2 space-y-2">
        <div class="flex flex-wrap gap-2">
          <div
            v-for="(attachment, idx) in pendingAttachments"
            :key="`${attachment.name}-${idx}`"
            class="flex items-center gap-2 rounded border border-border px-2 py-1 text-xs bg-muted"
          >
            <ImageIcon v-if="isImageAttachment(attachment)" class="w-3.5 h-3.5" />
            <FileText v-else class="w-3.5 h-3.5" />
            <span class="max-w-[170px] truncate">{{ attachment.name }}</span>
            <span class="opacity-70">{{ formatAttachmentSize(attachment.size) }}</span>
            <button class="hover:text-destructive" @click="removeAttachment(idx)">
              <X class="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
        <p class="text-xs text-muted-foreground">
          {{ formatAttachmentSize(totalPendingAttachmentBytes) }} attached · Max per file {{ formatAttachmentSize(MAX_ATTACHMENT_BYTES) }} · Max total {{ formatAttachmentSize(MAX_TOTAL_ATTACHMENT_BYTES) }}
        </p>
      </div>

      <p v-if="composerError" class="text-xs text-destructive mb-2">{{ composerError }}</p>

      <div class="flex gap-2 items-end">
        <button
          class="rounded-md border border-input p-2 hover:bg-accent disabled:opacity-50"
          :disabled="chat.isStreaming"
          @click="openPicker"
          title="Attach files"
        >
          <Paperclip class="w-4 h-4" />
        </button>
        <textarea
          ref="textareaRef"
          v-model="input"
          @keydown="handleKeydown"
          placeholder="Send a message..."
          rows="1"
          class="flex-1 resize-none rounded-md border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring min-h-[40px] max-h-[120px]"
        ></textarea>
        <button
          @click="send"
          :disabled="!canSend"
          class="rounded-md bg-primary text-primary-foreground p-2 hover:bg-primary/90 disabled:opacity-50 transition-colors"
        >
          <Send v-if="!chat.isStreaming" class="w-4 h-4" />
          <Square v-else class="w-4 h-4" />
        </button>
      </div>
    </div>
  </div>
</template>
