// web/src/views/LoginView.vue
<template>
  <div class="relative flex items-center justify-center h-screen bg-surface-0 overflow-hidden">
    <!-- Atmospheric glows -->
    <div class="pointer-events-none absolute inset-0">
      <div class="absolute top-1/4 left-1/3 w-[500px] h-[500px] bg-accent/[0.04] rounded-full blur-[120px]"></div>
      <div class="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] bg-accent-dim/[0.06] rounded-full blur-[100px]"></div>
    </div>

    <div class="relative w-full max-w-sm mx-4 animate-fade-in">
      <!-- Glass card -->
      <div class="glass rounded-2xl border border-edge p-8 shadow-glow">
        <!-- IO brand mark -->
        <div class="flex flex-col items-center mb-8">
          <div class="w-14 h-14 rounded-xl bg-accent/10 border border-accent/20 flex items-center justify-center mb-4 shadow-glow-sm">
            <span class="text-accent font-mono font-bold text-2xl tracking-tighter">IO</span>
          </div>
          <h1 class="text-xl font-semibold text-txt-primary tracking-tight">Welcome back</h1>
          <p class="text-sm text-txt-muted mt-1">Sign in to continue</p>
        </div>

        <form @submit.prevent="handleSignIn" class="space-y-5">
          <div>
            <label for="email" class="block text-xs font-medium text-txt-secondary mb-1.5 tracking-wide uppercase">Email</label>
            <input
              id="email"
              v-model="email"
              type="email"
              required
              autocomplete="email"
              class="w-full px-3.5 py-2.5 bg-surface-0/60 border border-edge rounded-xl text-txt-primary placeholder-txt-muted text-sm focus:outline-none focus:border-accent/50 focus:ring-1 focus:ring-accent/20 focus:shadow-glow-sm transition-all duration-200"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label for="password" class="block text-xs font-medium text-txt-secondary mb-1.5 tracking-wide uppercase">Password</label>
            <input
              id="password"
              v-model="password"
              type="password"
              required
              autocomplete="current-password"
              class="w-full px-3.5 py-2.5 bg-surface-0/60 border border-edge rounded-xl text-txt-primary placeholder-txt-muted text-sm focus:outline-none focus:border-accent/50 focus:ring-1 focus:ring-accent/20 focus:shadow-glow-sm transition-all duration-200"
              placeholder="••••••••"
            />
          </div>

          <div v-if="error" class="flex items-center gap-2 text-sm text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl px-3.5 py-2.5">
            <FluentIcon :paths='`<path d="m4.09 4.22.06-.07a.5.5 0 0 1 .63-.06l.07.06L10 9.29l5.15-5.14a.5.5 0 0 1 .63-.06l.07.06c.18.17.2.44.06.63l-.06.07L10.71 10l5.14 5.15c.18.17.2.44.06.63l-.06.07a.5.5 0 0 1-.63.06l-.07-.06L10 10.71l-5.15 5.14a.5.5 0 0 1-.63.06l-.07-.06a.5.5 0 0 1-.06-.63l.06-.07L9.29 10 4.15 4.85a.5.5 0 0 1-.06-.63l.06-.07-.06.07Z"/>`' :size="16" class="shrink-0" />
            {{ error }}
          </div>

          <button
            type="submit"
            :disabled="auth.loading"
            class="w-full py-2.5 px-4 bg-accent hover:bg-accent-glow disabled:opacity-50 disabled:cursor-not-allowed text-surface-0 font-semibold text-sm rounded-xl transition-all duration-200 shadow-glow-sm hover:shadow-glow"
          >
            {{ auth.loading ? 'Signing in…' : 'Sign in' }}
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import FluentIcon from '../components/FluentIcon.vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const auth = useAuthStore()
const router = useRouter()

const email = ref('')
const password = ref('')
const error = ref<string | null>(null)

async function handleSignIn() {
  error.value = null
  const err = await auth.signIn(email.value, password.value)
  if (err) {
    error.value = err
  } else {
    router.push('/chat')
  }
}
</script>

// web/src/views/LoginView.tsx
import { type FormEvent, useState } from "react";
import { useNavigate } from "react-router";
import { IoMark } from "@/components/IoMark";
import { useAuthStore } from "@/stores/auth";

export default function LoginView() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const login = useAuthStore((s) => s.login);
  const loading = useAuthStore((s) => s.loading);
  const navigate = useNavigate();

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");
    try {
      await login(email, password);
      navigate("/");
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Login failed");
    }
  };

  return (
    <div className="min-h-screen bg-[#161616] flex items-center justify-center relative overflow-hidden">
      {/* subtle dot grid */}
      <div
        className="absolute inset-0 opacity-[0.04]"
        style={{
          backgroundImage: "radial-gradient(circle, var(--base-teal) 1px, transparent 1px)",
          backgroundSize: "32px 32px",
        }}
      />
      {/* glow behind logo */}
      <div
        className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-[60%] w-[400px] h-[300px] rounded-full blur-3xl pointer-events-none"
        style={{ background: "radial-gradient(ellipse, rgba(69,162,158,0.12) 0%, transparent 70%)" }}
      />

      <div className="relative z-10 w-full max-w-[360px] mx-4">
        {/* Logo */}
        <div className="flex flex-col items-center mb-8 gap-3">
          <IoMark height={52} />
          <div className="text-center">
            <p className="text-[14px] font-mono text-zinc-600 tracking-widest uppercase mt-1">
              personal ai orchestrator
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="glass-card border border-white/[0.07] rounded-2xl p-6 space-y-4">
          {error && (
            <div className="text-[14px] font-mono text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl px-3 py-2">
              {error}
            </div>
          )}
          <div className="space-y-1">
            <label className="text-[14px] font-mono text-zinc-500 block">Email</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full bg-[#161616] border border-white/[0.08] rounded-xl px-3 py-2.5 text-sm text-zinc-200 font-mono placeholder:text-zinc-700 focus:outline-none focus:border-[#66FCF1]/40 focus:ring-1 focus:ring-[#66FCF1]/15 transition-colors"
              required
            />
          </div>
          <div className="space-y-1">
            <label className="text-[14px] font-mono text-zinc-500 block">Password</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••"
              className="w-full bg-[#161616] border border-white/[0.08] rounded-xl px-3 py-2.5 text-sm text-zinc-200 font-mono placeholder:text-zinc-700 focus:outline-none focus:border-[#66FCF1]/40 focus:ring-1 focus:ring-[#66FCF1]/15 transition-colors"
              required
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full text-[#1F2833] font-mono text-sm rounded-xl py-3 mt-1 transition-opacity hover:opacity-90 disabled:opacity-50 flex items-center justify-center gap-2"
            style={{ background: "var(--base-gradient)" }}
          >
            {loading ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-[#1F2833]/30 border-t-[#1F2833] rounded-full animate-spin" />
                Authenticating…
              </>
            ) : (
              "Sign In"
            )}
          </button>
        </form>
      </div>
    </div>
  );
}
