// packages/web/src/views/LoginView.tsx
import { useState } from "react";
import { useAuth } from "@/lib/auth";

export function LoginView() {
	const { signIn } = useAuth();
	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");
	const [error, setError] = useState<string | null>(null);
	const [loading, setLoading] = useState(false);

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setError(null);
		setLoading(true);

		const { error: err } = await signIn(email, password);
		if (err) {
			setError(err);
		}
		setLoading(false);
	}

	return (
		<div className="min-h-screen flex items-center justify-center relative z-10">
			{/* Orbs */}
			<div className="orb orb-1" />
			<div className="orb orb-2" />
			<div className="orb orb-3" />

			<div className="glass-card p-8 w-full max-w-sm">
				<div className="text-center mb-6">
					<h1 className="text-2xl font-bold gradient-text">IO</h1>
					<p className="text-sm text-[var(--color-muted-foreground)] mt-1">
						Sign in to your orchestrator
					</p>
				</div>

				<form onSubmit={handleSubmit} className="space-y-4">
					<div>
						<label htmlFor="email" className="block text-sm font-medium mb-1.5">
							Email
						</label>
						<input
							id="email"
							type="email"
							value={email}
							onChange={(e) => setEmail(e.target.value)}
							required
							className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
						/>
					</div>

					<div>
						<label htmlFor="password" className="block text-sm font-medium mb-1.5">
							Password
						</label>
						<input
							id="password"
							type="password"
							value={password}
							onChange={(e) => setPassword(e.target.value)}
							required
							className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
						/>
					</div>

					{error && (
						<p className="text-sm text-[var(--color-destructive)]">{error}</p>
					)}

					<button
						type="submit"
						disabled={loading}
						className="w-full py-2.5 rounded-md bg-[var(--color-accent)] text-white font-medium text-sm hover:opacity-90 transition-opacity disabled:opacity-50"
					>
						{loading ? "Signing in..." : "Sign In"}
					</button>
				</form>
			</div>
		</div>
	);
}

// web/src/views/LoginView.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from "@/stores/auth";

const auth = useAuthStore();
const router = useRouter();
const email = ref("");
const password = ref("");
const error = ref("");

async function handleLogin() {
  error.value = "";
  try {
    await auth.login(email.value, password.value);
    router.push("/");
  } catch (err: any) {
    error.value = err.message ?? "Login failed";
  }
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center bg-background p-4">
    <div class="w-full max-w-sm space-y-6">
      <!-- Logo -->
      <div class="text-center">
        <div class="text-4xl mb-2">🤖</div>
        <h1 class="text-2xl font-bold">IO</h1>
        <p class="text-sm text-muted-foreground mt-1">Sign in to your dashboard</p>
      </div>

      <!-- Form -->
      <form @submit.prevent="handleLogin" class="space-y-4">
        <div>
          <label class="text-sm font-medium" for="email">Email</label>
          <input
            id="email"
            v-model="email"
            type="email"
            required
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
            placeholder="you@example.com"
          />
        </div>
        <div>
          <label class="text-sm font-medium" for="password">Password</label>
          <input
            id="password"
            v-model="password"
            type="password"
            required
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
            placeholder="••••••••"
          />
        </div>

        <div v-if="error" class="text-sm text-destructive">{{ error }}</div>

        <button
          type="submit"
          :disabled="auth.loading"
          class="w-full rounded-md bg-primary text-primary-foreground px-4 py-2 text-sm font-medium hover:bg-primary/90 disabled:opacity-50 transition-colors"
        >
          {{ auth.loading ? "Signing in..." : "Sign In" }}
        </button>
      </form>
    </div>
  </div>
</template>
