// packages/web/src/views/SchedulesView.tsx
import { api } from '@/lib/api';
import { Calendar, Pause, Play, Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';

interface Schedule {
	id: string;
	name: string;
	targetType: 'squad' | 'orchestrator';
	targetId: string | null;
	cron: string;
	prompt: string;
	enabled: boolean;
	lastRun: string | null;
	nextRun: string | null;
}

export function SchedulesView() {
	const [schedules, setSchedules] = useState<Schedule[]>([]);
	const [tab, setTab] = useState<'all' | 'squad' | 'orchestrator'>('all');
	const [showCreate, setShowCreate] = useState(false);
	const [form, setForm] = useState({
		name: '',
		cron: '',
		prompt: '',
		targetType: 'orchestrator' as const,
	});

	useEffect(() => {
		loadSchedules();
	}, []);

	function loadSchedules() {
		api
			.get<{ schedules: Schedule[] }>('/schedules')
			.then((d) => setSchedules(d.schedules))
			.catch(() => {});
	}

	const filtered = schedules.filter((s) => tab === 'all' || s.targetType === tab);

	async function handleCreate() {
		if (!form.name || !form.cron || !form.prompt) return;
		try {
			await api.post('/schedules', form);
			toast.success(`Schedule "${form.name}" created`);
			setShowCreate(false);
			setForm({ name: '', cron: '', prompt: '', targetType: 'orchestrator' });
			loadSchedules();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to create');
		}
	}

	async function handleToggle(id: string, enabled: boolean) {
		try {
			await api.patch(`/schedules/${id}`, { enabled: !enabled });
			loadSchedules();
		} catch {
			toast.error('Failed to toggle schedule');
		}
	}

	async function handleDelete(id: string) {
		try {
			await api.delete(`/schedules/${id}`);
			toast.success('Schedule deleted');
			loadSchedules();
		} catch {
			toast.error('Failed to delete');
		}
	}

	return (
		<div className="h-full overflow-y-auto p-6">
			<header className="flex items-center justify-between mb-6">
				<div>
					<h1 className="text-2xl font-bold gradient-text">Schedules</h1>
					<p className="text-sm text-[var(--color-muted-foreground)] mt-1">
						Automated cron-based tasks
					</p>
				</div>
				<button
					type="button"
					onClick={() => setShowCreate(true)}
					className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[var(--color-accent)] text-white text-sm hover:opacity-90"
				>
					<Plus size={16} /> New Schedule
				</button>
			</header>

			{/* Tabs */}
			<div className="flex gap-1 mb-4 p-1 rounded-lg bg-white/3 w-fit">
				{(['all', 'orchestrator', 'squad'] as const).map((t) => (
					<button
						key={t}
						type="button"
						onClick={() => setTab(t)}
						className={`px-3 py-1.5 rounded-md text-xs font-medium transition-colors ${
							tab === t
								? 'bg-white/10 text-[var(--color-foreground)]'
								: 'text-[var(--color-muted-foreground)]'
						}`}
					>
						{t === 'all' ? 'All' : t === 'orchestrator' ? 'IO' : 'Squad'}
					</button>
				))}
			</div>

			{/* Create form */}
			{showCreate && (
				<div className="glass-card p-4 mb-6 space-y-3">
					<h3 className="font-semibold">New Schedule</h3>
					<input
						type="text"
						placeholder="Name"
						value={form.name}
						onChange={(e) => setForm({ ...form, name: e.target.value })}
						className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
					/>
					<input
						type="text"
						placeholder="Cron expression (e.g. 0 9 * * 1-5)"
						value={form.cron}
						onChange={(e) => setForm({ ...form, cron: e.target.value })}
						className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)] font-mono"
					/>
					<textarea
						placeholder="Prompt to execute"
						value={form.prompt}
						onChange={(e) => setForm({ ...form, prompt: e.target.value })}
						rows={3}
						className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)] resize-none"
					/>
					<div className="flex gap-2">
						<button
							type="button"
							onClick={handleCreate}
							className="px-3 py-1.5 rounded-md bg-[var(--color-accent)] text-white text-sm"
						>
							Create
						</button>
						<button
							type="button"
							onClick={() => setShowCreate(false)}
							className="px-3 py-1.5 rounded-md bg-white/5 text-sm"
						>
							Cancel
						</button>
					</div>
				</div>
			)}

			{/* Table */}
			<div className="space-y-2">
				{filtered.map((sched) => (
					<div key={sched.id} className="glass-card p-4 flex items-center gap-4">
						<div className="flex-1">
							<div className="flex items-center gap-2">
								<Calendar size={14} className="text-[var(--color-accent)]" />
								<span className="font-medium text-sm">{sched.name}</span>
								<span className="text-xs px-2 py-0.5 rounded-full bg-white/5 text-[var(--color-muted-foreground)]">
									{sched.targetType}
								</span>
							</div>
							<p className="text-xs text-[var(--color-muted-foreground)] mt-1 font-mono">
								{sched.cron}
							</p>
							<p className="text-xs text-[var(--color-muted-foreground)] mt-0.5 truncate max-w-md">
								{sched.prompt}
							</p>
						</div>
						<div className="flex items-center gap-2">
							<button
								type="button"
								onClick={() => handleToggle(sched.id, sched.enabled)}
								className={`p-1.5 rounded-md transition-colors ${
									sched.enabled
										? 'text-[var(--color-success)] hover:bg-[var(--color-success)]/10'
										: 'text-[var(--color-muted)] hover:bg-white/5'
								}`}
								title={sched.enabled ? 'Pause' : 'Resume'}
							>
								{sched.enabled ? <Play size={14} /> : <Pause size={14} />}
							</button>
							<button
								type="button"
								onClick={() => handleDelete(sched.id)}
								className="p-1.5 rounded-md text-[var(--color-muted-foreground)] hover:text-[var(--color-destructive)] hover:bg-[var(--color-destructive)]/10 transition-colors"
							>
								<Trash2 size={14} />
							</button>
						</div>
					</div>
				))}
			</div>

			{filtered.length === 0 && (
				<div className="text-center py-12 text-[var(--color-muted-foreground)]">
					<Calendar size={48} className="mx-auto mb-3 opacity-30" />
					<p>No schedules. Click New Schedule to create one.</p>
				</div>
			)}
		</div>
	);
}

// web/src/views/SchedulesView.vue
<script setup lang="ts">
import { ref, onMounted, computed } from "vue";
import { apiGet, apiPost, apiDelete, apiPut } from "@/lib/api";
import { Clock, Plus, Trash2 } from "lucide-vue-next";
import { getSquadLabelStyle } from "@/lib/squad-colors";

interface Schedule {
  id: string;
  type: "squad" | "io";
  squad_id: string | null;
  cron: string;
  agenda: string;
  prompt: string;
  enabled: number;
  last_run: string | null;
}

interface Squad {
  id: string;
  name: string;
  color: string;
}

const schedules = ref<Schedule[]>([]);
const squads = ref<Squad[]>([]);
const loading = ref(true);
const tab = ref<"squad" | "io">("squad");
const showAdd = ref(false);
const newSchedule = ref({ type: "squad" as "squad" | "io", cron: "", squad_id: "", agenda: "triage", prompt: "" });

onMounted(async () => {
  try {
    const squadData = await apiGet("/squads");
    squads.value = squadData.squads;
    if (squads.value.length > 0) {
      newSchedule.value.squad_id = squads.value[0].id;
    }
    schedules.value = await apiGet("/schedules");
  } finally {
    loading.value = false;
  }
});

const filteredSchedules = () => schedules.value.filter((s) => s.type === tab.value);

async function addSchedule() {
  const body: any = {
    type: newSchedule.value.type,
    cron: newSchedule.value.cron,
    squad_id: newSchedule.value.squad_id,
  };
  if (newSchedule.value.type === "squad") {
    if (!newSchedule.value.squad_id) return;
    body.squad_id = newSchedule.value.squad_id;
    body.agenda = newSchedule.value.agenda;
  } else {
    body.prompt = newSchedule.value.prompt;
  }
  const schedule = await apiPost("/schedules", body);
  schedules.value.push(schedule);
  showAdd.value = false;
}

function getSquadById(squadId: string | null): Squad | undefined {
  if (!squadId) return undefined;
  return squads.value.find((s) => s.id === squadId);
}

const decoratedSchedules = computed(() =>
  filteredSchedules().map((schedule) => ({
    ...schedule,
    squad: getSquadById(schedule.squad_id),
  }))
);

async function toggleSchedule(schedule: Schedule) {
  const enabled = !schedule.enabled;
  await apiPut(`/schedules/${schedule.id}`, { enabled });
  schedule.enabled = enabled ? 1 : 0;
}

async function deleteSchedule(id: string) {
  await apiDelete(`/schedules/${id}`);
  schedules.value = schedules.value.filter((s) => s.id !== id);
}

function getSquadName(squadId: string | null): string {
  if (!squadId) return "Unknown squad";
  return squads.value.find((s) => s.id === squadId)?.name ?? squadId;
}
</script>

<template>
  <div class="p-6">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold">Schedules</h1>
      <button
        @click="showAdd = !showAdd"
        class="inline-flex items-center gap-1 px-3 py-1.5 text-sm rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
      >
        <Plus class="w-4 h-4" /> Add Schedule
      </button>
    </div>

    <!-- Tabs -->
    <div class="flex gap-1 border-b border-border mb-4">
      <button
        v-for="t in (['squad', 'io'] as const)"
        :key="t"
        @click="tab = t"
        class="px-4 py-2 text-sm font-medium border-b-2 transition-colors"
        :class="tab === t ? 'border-primary text-foreground' : 'border-transparent text-muted-foreground hover:text-foreground'"
      >
        {{ t === 'squad' ? 'Squad Schedules' : 'IO Schedules' }}
      </button>
    </div>

    <!-- Add form -->
    <div v-if="showAdd" class="border border-border rounded-lg p-4 mb-4 space-y-3">
      <div class="grid grid-cols-2 gap-3">
        <div>
          <label class="text-sm font-medium">Type</label>
          <select v-model="newSchedule.type" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">
            <option value="squad">Squad</option>
            <option value="io">IO</option>
          </select>
        </div>
        <div>
          <label class="text-sm font-medium">Cron Expression</label>
          <input v-model="newSchedule.cron" placeholder="0 9 * * 1-5" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
        </div>
      </div>
      <div>
        <label class="text-sm font-medium">Target Squad</label>
        <select
          v-model="newSchedule.squad_id"
          class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
        >
          <option v-for="squad in squads" :key="squad.id" :value="squad.id">
            {{ squad.name }}
          </option>
        </select>
      </div>
      <div v-if="newSchedule.type === 'squad'">
        <label class="text-sm font-medium">Agenda</label>
        <select v-model="newSchedule.agenda" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">
          <option value="triage">Triage</option>
          <option value="prioritize">Prioritize</option>
          <option value="ideation">Ideation</option>
        </select>
      </div>
      <div v-else>
        <label class="text-sm font-medium">Prompt</label>
        <textarea v-model="newSchedule.prompt" rows="2" class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"></textarea>
      </div>
      <button
        @click="addSchedule"
        :disabled="!newSchedule.squad_id"
        class="px-4 py-2 text-sm rounded-md bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed"
      >
        Save
      </button>
    </div>

    <div v-if="loading" class="text-muted-foreground">Loading...</div>

    <div v-else-if="filteredSchedules().length === 0" class="text-center py-12 text-muted-foreground">
      <Clock class="w-12 h-12 mx-auto mb-3 opacity-50" />
      <p>No {{ tab }} schedules configured.</p>
    </div>

    <div v-else class="space-y-2">
      <div v-for="schedule in decoratedSchedules" :key="schedule.id" class="flex items-center justify-between border border-border rounded-lg px-4 py-3">
        <div>
          <div class="text-sm font-medium font-mono">{{ schedule.cron }}</div>
          <div v-if="schedule.squad" class="mt-1">
            <span class="text-xs px-2 py-0.5 rounded-full" :style="getSquadLabelStyle(schedule.squad.color)">
              {{ schedule.squad.name }}
            </span>
          </div>
          <div class="text-xs text-muted-foreground mt-0.5">
            {{ schedule.type === 'squad' ? `Agenda: ${schedule.agenda}` : schedule.prompt.slice(0, 60) }}
          </div>
          <div class="text-xs text-muted-foreground mt-0.5">
            Squad: {{ getSquadName(schedule.squad_id) }}
          </div>
        </div>
        <div class="flex items-center gap-3">
          <button
            @click="toggleSchedule(schedule)"
            class="relative w-10 h-5 rounded-full transition-colors"
            :class="schedule.enabled ? 'bg-primary' : 'bg-muted'"
          >
            <span class="absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform" :class="schedule.enabled ? 'translate-x-5' : 'translate-x-0.5'"></span>
          </button>
          <button @click="deleteSchedule(schedule.id)" class="p-1.5 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive">
            <Trash2 class="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
