// web/src/views/SkillsView.tsx
import { Pencil, Search, Trash2, Zap } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Chip, DangerBtn, MarkdownRenderer, PrimaryBtn, SecondaryBtn } from "@/components/ui";
import { notifyError, notifySuccess } from "@/lib/notify";
import { type ParsedSkill, parseSkillContent } from "@/lib/skill-frontmatter";
import { useAuthStore } from "@/stores/auth";

type SkillSource = "installed" | "awesome-copilot" | "skillssh";

interface InstalledSkill {
  name: string;
  slug: string;
  description: string;
  path: string;
}

interface RemoteSkill {
  slug: string;
  name: string;
  description: string;
  source: Exclude<SkillSource, "installed">;
  sourceRepo?: string;
  installs?: number;
}

interface SkillDetailState {
  content?: string;
  parsed?: ParsedSkill;
  loading?: boolean;
  error?: string;
}

interface SelectedSkill {
  source: SkillSource;
  slug: string;
}

const SECTION_HEADER = "text-[10px] font-mono text-zinc-700 uppercase tracking-wider";

function skillKey(source: SkillSource, slug: string): string {
  return `${source}:${slug}`;
}

async function requestJson<T>(path: string, init: RequestInit = {}): Promise<T> {
  const token = useAuthStore.getState().token;
  const headers = new Headers(init.headers ?? {});

  if (!(init.body instanceof FormData) && !headers.has("Content-Type")) {
    headers.set("Content-Type", "application/json");
  }
  if (token) {
    headers.set("Authorization", `Bearer ${token}`);
  }

  const response = await fetch(path, { ...init, headers });
  if (!response.ok) {
    let message = `Request failed (${response.status})`;
    try {
      const errorBody = (await response.json()) as { error?: string };
      if (errorBody.error) {
        message = errorBody.error;
      }
    } catch {
      const text = await response.text();
      if (text) {
        message = text;
      }
    }
    throw new Error(message);
  }

  const text = await response.text();
  return (text ? JSON.parse(text) : undefined) as T;
}

function frontmatterLabel(key: string): string {
  return key.replace(/[_-]+/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function frontmatterValue(value: unknown): string {
  if (Array.isArray(value)) {
    return value.join(", ");
  }
  return String(value);
}

export default function SkillsView() {
  const [installedSkills, setInstalledSkills] = useState<InstalledSkill[]>([]);
  const [remoteSkills, setRemoteSkills] = useState<RemoteSkill[]>([]);
  const [source, setSource] = useState<SkillSource>("installed");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<SelectedSkill | null>(null);
  const [detailState, setDetailState] = useState<Record<string, SkillDetailState>>({});
  const [loadingInstalled, setLoadingInstalled] = useState(true);
  const [loadingRemote, setLoadingRemote] = useState(false);
  const [pageError, setPageError] = useState("");
  const [actionKey, setActionKey] = useState("");
  const [editMode, setEditMode] = useState(false);
  const [editContent, setEditContent] = useState("");

  const loadInstalledSkills = useCallback(async () => {
    setLoadingInstalled(true);
    try {
      const data = await requestJson<InstalledSkill[]>("/api/skills");
      setInstalledSkills(data);
      setPageError("");
    } catch (error) {
      setPageError(error instanceof Error ? error.message : "Failed to load skills");
    } finally {
      setLoadingInstalled(false);
    }
  }, []);

  useEffect(() => {
    void loadInstalledSkills();
  }, [loadInstalledSkills]);

  useEffect(() => {
    if (source === "installed") return;

    const timeout = window.setTimeout(async () => {
      setLoadingRemote(true);
      try {
        const query = new URLSearchParams({ source });
        if (search.trim()) {
          query.set("q", search.trim());
        }
        const data = await requestJson<RemoteSkill[]>(`/api/skills/discover?${query.toString()}`);
        setRemoteSkills(data);
        setPageError("");
      } catch (error) {
        setRemoteSkills([]);
        setPageError(error instanceof Error ? error.message : "Failed to search remote skills");
      } finally {
        setLoadingRemote(false);
      }
    }, 220);

    return () => window.clearTimeout(timeout);
  }, [search, source]);

  const installedLookup = useMemo(() => {
    const map = new Map<string, InstalledSkill>();
    for (const skill of installedSkills) {
      map.set(skill.slug, skill);
    }
    return map;
  }, [installedSkills]);

  const visibleSkills = useMemo(() => {
    if (source === "installed") {
      const query = search.trim().toLowerCase();
      if (!query) return installedSkills;
      return installedSkills.filter((skill) =>
        [skill.name, skill.slug, skill.description].some((value) => value?.toLowerCase().includes(query)),
      );
    }
    return remoteSkills;
  }, [installedSkills, remoteSkills, search, source]);

  useEffect(() => {
    if (visibleSkills.length === 0) {
      if (selected?.source === source) {
        setSelected(null);
      }
      return;
    }

    const currentVisible =
      selected && selected.source === source && visibleSkills.some((skill) => skill.slug === selected.slug);

    if (!currentVisible) {
      setSelected({ source, slug: visibleSkills[0].slug });
      setEditMode(false);
    }
  }, [selected, source, visibleSkills]);

  const selectedSkill = useMemo(() => {
    if (!selected) return null;
    if (selected.source === "installed") {
      return installedSkills.find((skill) => skill.slug === selected.slug) ?? null;
    }
    return remoteSkills.find((skill) => skill.slug === selected.slug) ?? null;
  }, [installedSkills, remoteSkills, selected]);

  useEffect(() => {
    if (!selectedSkill || !selected) return;

    const key = skillKey(selected.source, selected.slug);
    const cached = detailState[key];
    if (cached?.loading || cached?.content || cached?.error) return;

    setDetailState((current) => ({
      ...current,
      [key]: { ...current[key], loading: true, error: "" },
    }));

    const loadSkillDetail = async () => {
      try {
        const content =
          selected.source === "installed"
            ? (await requestJson<{ content: string }>(`/api/skills/${encodeURIComponent(selected.slug)}/content`))
                .content
            : (
                await requestJson<{ content: string }>(
                  `/api/skills/preview?${new URLSearchParams({
                    source: selected.source,
                    slug: selected.slug,
                    ...("sourceRepo" in selectedSkill && selectedSkill.sourceRepo
                      ? { sourceRepo: selectedSkill.sourceRepo }
                      : {}),
                  }).toString()}`,
                )
              ).content;

        setDetailState((current) => ({
          ...current,
          [key]: { content, parsed: parseSkillContent(content), loading: false, error: "" },
        }));
      } catch (error) {
        setDetailState((current) => ({
          ...current,
          [key]: {
            ...current[key],
            loading: false,
            error: error instanceof Error ? error.message : "Unable to load skill details",
          },
        }));
      }
    };

    void loadSkillDetail();
  }, [detailState, selected, selectedSkill]);

  const selectedKey = selected ? skillKey(selected.source, selected.slug) : "";
  const selectedDetail = selected ? detailState[selectedKey] : undefined;
  const selectedFrontmatter = selectedDetail?.parsed?.frontmatter ?? {};
  const selectedBody = selectedDetail?.parsed?.body ?? "";
  const isInstalled = !!(selectedSkill && installedLookup.has(selectedSkill.slug));

  const getListMeta = (skill: InstalledSkill | RemoteSkill): string => {
    const key = skillKey(source, skill.slug);
    const detail = detailState[key];
    const installs =
      source === "skillssh" && "installs" in skill && skill.installs
        ? `${skill.installs.toLocaleString()} installs`
        : undefined;
    const author =
      typeof detail?.parsed?.frontmatter.author === "string"
        ? detail.parsed.frontmatter.author
        : "sourceRepo" in skill && skill.sourceRepo
          ? skill.sourceRepo
          : source === "awesome-copilot"
            ? "awesome-copilot"
            : "community";
    return `${author}${installs ? ` · ${installs}` : ""}`;
  };

  const startEditing = () => {
    if (!selectedDetail?.content || !selected || selected.source !== "installed") return;
    setEditContent(selectedDetail.content);
    setEditMode(true);
  };

  const saveEditedContent = async () => {
    if (selected?.source !== "installed") return;

    const key = skillKey(selected.source, selected.slug);
    setActionKey(`save:${key}`);
    try {
      await requestJson(`/api/skills/${encodeURIComponent(selected.slug)}/content`, {
        method: "PUT",
        body: JSON.stringify({ content: editContent }),
      });
      setDetailState((current) => ({
        ...current,
        [key]: { content: editContent, parsed: parseSkillContent(editContent), loading: false, error: "" },
      }));
      setEditMode(false);
      setPageError("");
    } catch (error) {
      setPageError(error instanceof Error ? error.message : "Failed to save skill");
    } finally {
      setActionKey("");
    }
  };

  const removeInstalledSkill = async () => {
    if (!selectedSkill || !selected || selected.source !== "installed") return;

    setActionKey(`remove:${selected.slug}`);
    try {
      await requestJson(`/api/skills/${encodeURIComponent(selected.slug)}`, { method: "DELETE" });
      setInstalledSkills((current) => current.filter((skill) => skill.slug !== selected.slug));
      setDetailState((current) => {
        const next = { ...current };
        delete next[skillKey("installed", selected.slug)];
        return next;
      });
      setPageError("");
      notifySuccess("Skill removed");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to remove skill";
      setPageError(message);
      notifyError(message);
    } finally {
      setActionKey("");
      setEditMode(false);
    }
  };

  const installRemoteSkill = async () => {
    if (!selectedSkill || !selected || selected.source === "installed" || isInstalled) return;

    setActionKey(`install:${selected.slug}`);
    try {
      await requestJson("/api/skills", {
        method: "POST",
        body: JSON.stringify({
          source: selected.source,
          slug: selected.slug,
          ...("sourceRepo" in selectedSkill && selectedSkill.sourceRepo
            ? { sourceRepo: selectedSkill.sourceRepo }
            : {}),
        }),
      });
      await loadInstalledSkills();
      setPageError("");
      notifySuccess("Skill installed");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to install skill";
      setPageError(message);
      notifyError(message);
    } finally {
      setActionKey("");
    }
  };

  return (
    <div className="h-full">
      <div className="grid h-full min-h-0 grid-cols-[16rem_minmax(0,1fr)]">
        <aside className={`min-h-0 overflow-hidden flex flex-col border-r border-white/[0.06]`}>
          <div className="border-b border-white/[0.06] p-3">
            <div className="relative mb-3">
              <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-zinc-700" />
              <input
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder="Search skills..."
                className={`w-full pl-9 bg-[#181818] border border-white/[0.06] rounded-xl px-3 py-2 text-[11px] text-zinc-300 font-mono placeholder:text-zinc-700 focus:outline-none focus:border-[#66FCF1]/30`}
              />
            </div>

            <div className="space-y-1">
              {(
                [
                  ["installed", "Installed"],
                  ["awesome-copilot", "Awesome Copilot"],
                  ["skillssh", "skills.sh"],
                ] as const
              ).map(([tabKey, label]) => {
                const active = source === tabKey;
                return (
                  <button
                    key={tabKey}
                    onClick={() => setSource(tabKey)}
                    className={`w-full text-left cursor-pointer px-2.5 py-1.5 rounded-lg text-[11px] font-mono transition-colors ${
                      active ? "text-[#66FCF1]" : "text-zinc-500 hover:text-zinc-300 hover:bg-white/[0.04]"
                    }`}
                    style={active ? { background: "rgba(102,252,241,0.10)" } : undefined}
                  >
                    {label}
                  </button>
                );
              })}
            </div>
          </div>

          <div className="min-h-0 flex-1 overflow-y-auto">
            {pageError && (
              <div className="border-b border-red-500/15 bg-red-500/6 px-3 py-2 text-[11px] font-mono text-red-300">
                {pageError}
              </div>
            )}

            {(loadingInstalled || loadingRemote) && visibleSkills.length === 0 ? (
              <div className="px-4 py-5 text-[11px] font-mono text-zinc-600">Loading skills…</div>
            ) : visibleSkills.length === 0 ? (
              <div className="px-4 py-5 text-[11px] font-mono text-zinc-700">No skills found.</div>
            ) : (
              visibleSkills.map((skill) => {
                const active = selected?.source === source && selected.slug === skill.slug;
                return (
                  <button
                    key={`${source}:${skill.slug}`}
                    onClick={() => {
                      setSelected({ source, slug: skill.slug });
                      setEditMode(false);
                    }}
                    className={`w-full cursor-pointer border-l-2 px-3 py-3 text-left transition-colors ${
                      active ? "border-[#66FCF1]" : "border-transparent hover:bg-white/[0.03]"
                    }`}
                    style={active ? { background: "var(--base-dark-teal)" } : undefined}
                  >
                    <div className="truncate text-[11px] font-mono text-zinc-200">{skill.name || skill.slug}</div>
                    <div
                      className="mt-1 text-[10px] leading-relaxed text-zinc-600 line-clamp-2"
                      style={active ? { color: "var(--base-gray)" } : undefined}
                    >
                      {skill.description
                        ? skill.description.length > 100
                          ? `${skill.description.slice(0, 100)}…`
                          : skill.description
                        : "No description"}
                    </div>
                    <div
                      className="mt-2 truncate text-[9px] font-mono text-zinc-700"
                      style={active ? { color: "var(--base-gray)" } : undefined}
                    >
                      {getListMeta(skill)}
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </aside>

        <section className={`min-h-0 overflow-hidden flex flex-col`}>
          {!selectedSkill ? (
            <div className="flex h-full items-center justify-center align-center px-6 text-center">
              <div>
                <div
                  className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-[#66FCF1]/20"
                  style={{ background: "rgba(102,252,241,0.10)" }}
                >
                  <Zap className="h-6 w-6 text-[#66FCF1]" />
                </div>
                <p className="mt-4 text-sm text-zinc-400">
                  Select a skill to inspect its front matter and prompt body.
                </p>
              </div>
            </div>
          ) : (
            <div className="flex min-h-0 flex-1 flex-col ">
              <div className="border-b border-white/[0.06] p-6">
                <div className="flex flex-wrap items-center justify-between gap-4">
                  <div className="flex items-start gap-4 items-center">
                    <div
                      className="flex h-12 w-12 items-center justify-center rounded-full border border-[#66FCF1]/20"
                      style={{ background: "rgba(102,252,241,0.10)" }}
                    >
                      <Zap className="h-5 w-5 text-[#66FCF1]" />
                    </div>
                    <div className="flex justify-center">
                      <div className="flex flex-wrap items-center gap-2">
                        <h1
                          className="text-3xl leading-none text-white"
                          style={{ fontFamily: "'Bebas Neue', sans-serif" }}
                        >
                          {selectedDetail?.parsed?.frontmatter.name || selectedSkill.name || selectedSkill.slug}
                        </h1>
                        {typeof selectedFrontmatter.version === "string" ? (
                          <Chip variant="info">v{selectedFrontmatter.version}</Chip>
                        ) : (
                          <Chip variant="muted">unversioned</Chip>
                        )}
                        <Chip variant={isInstalled ? "success" : "muted"}>{isInstalled ? "installed" : "remote"}</Chip>
                      </div>
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-2">
                    {selected?.source === "installed" ? (
                      <>
                        <SecondaryBtn onClick={startEditing} className="px-3 py-1.5">
                          <Pencil className="h-3.5 w-3.5" />
                          Edit
                        </SecondaryBtn>
                        <DangerBtn onClick={() => void removeInstalledSkill()} className="px-3 py-1.5">
                          <Trash2 className="h-3.5 w-3.5" />
                          {actionKey === `remove:${selected?.slug}` ? "Removing…" : "Remove"}
                        </DangerBtn>
                      </>
                    ) : (
                      <PrimaryBtn
                        onClick={isInstalled ? undefined : () => void installRemoteSkill()}
                        className="px-3 py-1.5"
                      >
                        {actionKey === `install:${selected?.slug}`
                          ? "Installing…"
                          : isInstalled
                            ? "Installed"
                            : "Install"}
                      </PrimaryBtn>
                    )}
                  </div>
                </div>
              </div>

              <div className="min-h-0 flex-1 overflow-y-auto p-6 space-y-6">
                {selectedDetail?.loading ? (
                  <div className="text-[11px] font-mono text-zinc-600">Loading skill detail…</div>
                ) : selectedDetail?.error ? (
                  <div className="rounded-2xl border border-red-500/15 bg-red-500/6 px-4 py-3 text-[11px] font-mono text-red-300">
                    {selectedDetail.error}
                  </div>
                ) : editMode ? (
                  <div className={`p-5 space-y-4`}>
                    <div className={SECTION_HEADER}>Editing skill markdown</div>
                    <textarea
                      value={editContent}
                      onChange={(event) => setEditContent(event.target.value)}
                      className="min-h-[440px] w-full resize-y rounded-2xl border border-white/[0.06] bg-[#181818] px-4 py-3 font-mono text-[11px] text-zinc-300 placeholder:text-zinc-700 focus:border-[#66FCF1]/30 focus:outline-none"
                    />
                    <div className="flex flex-wrap gap-2">
                      <PrimaryBtn onClick={() => void saveEditedContent()} className="px-3 py-1.5">
                        {actionKey === `save:${selectedKey}` ? "Saving…" : "Save"}
                      </PrimaryBtn>
                      <SecondaryBtn onClick={() => setEditMode(false)} className="px-3 py-1.5">
                        Cancel
                      </SecondaryBtn>
                    </div>
                  </div>
                ) : (
                  <>
                    <div className={`p-2`}>
                      <div className={SECTION_HEADER}>Front Matter</div>
                      {Object.keys(selectedFrontmatter).filter((k) => k !== "name" && k !== "description").length ===
                      0 ? (
                        <div className="mt-4 text-[11px] font-mono text-zinc-700">No front matter metadata found.</div>
                      ) : (
                        <div className="mt-4 space-y-0">
                          {Object.entries(selectedFrontmatter)
                            .filter(([key]) => key !== "name")
                            .map(([key, value]) => (
                              <div
                                key={key}
                                className="grid grid-cols-[200px_1fr] gap-2 border-b border-white/[0.04] py-3 first:pt-0 last:border-b-0 last:pb-0"
                              >
                                <span className="text-[11px] font-mono text-zinc-500">
                                  {frontmatterLabel(key)}
                                </span>
                                <span className="text-[11px] font-mono text-zinc-300 break-words min-w-0 text-left">
                                  {frontmatterValue(value)}
                                </span>
                              </div>
                            ))}
                        </div>
                      )}
                    </div>

                    <div className={`p-5`}>
                      <div className={SECTION_HEADER}>Body</div>
                      {selectedBody ? (
                        <MarkdownRenderer content={selectedBody} className="mt-4" />
                      ) : (
                        <div className="mt-4 text-[11px] font-mono text-zinc-700">This skill has no markdown body.</div>
                      )}
                    </div>
                  </>
                )}
              </div>
            </div>
          )}
        </section>
      </div>
    </div>
  );
}

// web/src/views/SkillsView.vue
<script setup lang="ts">
  import { ref, computed, onMounted } from "vue";
  import { apiGet, apiPost, apiPut, apiDelete } from "@/lib/api";
  import { Puzzle, Plus, Trash2, Pencil, Save, X, Search, Globe } from "lucide-vue-next";
  import MarkdownContent from "@/components/MarkdownContent.vue";
  import { extractSkillFrontmatter } from "@/lib/skill-frontmatter";

  interface Skill {
    name: string;
    slug: string;
    description: string;
    path: string;
  }

  interface DiscoveredSkill {
    slug: string;
    name: string;
    description: string;
    source: "awesome-copilot" | "skillssh";
  }

  const DEFAULT_SKILL_TEMPLATE =
    "# My Skill\n\nA brief description of what this skill does.\n\n## Usage\n\nInstructions for how to use this skill...\n";

  // ---- Installed skills state ----
  const skills = ref<Skill[]>([]);
  const loading = ref(true);
  const showAddForm = ref(false);
  const addMode = ref<"git" | "create">("git");
  const newSkillUrl = ref("");
  const newSkillTitle = ref("");
  const newSkillContent = ref(DEFAULT_SKILL_TEMPLATE);
  const adding = ref(false);
  const error = ref("");

  // Derives a display slug from the title using the same normalisation rules as
  // createSkill() in src/copilot/skills.ts so the user sees the exact slug that
  // will be used before submitting the form.
  const newSkillSlug = computed(() =>
    newSkillTitle.value
      .trim()
      .replace(/[^a-z0-9-]/gi, "-")
      .toLowerCase()
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
  );

  // View/Edit state
  const selectedSkill = ref<Skill | null>(null);
  const skillContent = ref("");
  const editMode = ref(false);
  const editContent = ref("");
  const loadingContent = ref(false);

  const installedSkillContent = computed(() => extractSkillFrontmatter(skillContent.value));
  const previewSkillContent = computed(() => extractSkillFrontmatter(previewContent.value));

  // ---- Discovery state ----
  type Tab = "installed" | "discover";
  const activeTab = ref<Tab>("installed");
  const discoverSource = ref<"awesome-copilot" | "skillssh">("awesome-copilot");
  const discoverQuery = ref("");
  const discoveredSkills = ref<DiscoveredSkill[]>([]);
  const discoverLoading = ref(false);
  const discoverError = ref("");
  const selectedDiscovered = ref<DiscoveredSkill | null>(null);
  const previewContent = ref("");
  const previewLoading = ref(false);
  const installingSlug = ref("");

  async function fetchSkills() {
    loading.value = true;
    try {
      skills.value = await apiGet("/skills");
    } finally {
      loading.value = false;
    }
  }

  function openAddForm(mode: "git" | "create") {
    addMode.value = mode;
    showAddForm.value = true;
    error.value = "";
  }

  function cancelAddForm() {
    showAddForm.value = false;
    newSkillUrl.value = "";
    newSkillTitle.value = "";
    newSkillContent.value = DEFAULT_SKILL_TEMPLATE;
    error.value = "";
  }

  async function addSkillFromGit() {
    if (!newSkillUrl.value.trim()) return;
    adding.value = true;
    error.value = "";
    try {
      await apiPost("/skills", { url: newSkillUrl.value.trim() });
      cancelAddForm();
      await fetchSkills();
    } catch (err: any) {
      error.value = err.message || "Failed to install skill";
    } finally {
      adding.value = false;
    }
  }

  async function createSkill() {
    if (!newSkillTitle.value.trim() || !newSkillContent.value.trim()) return;
    adding.value = true;
    error.value = "";
    try {
      await apiPost("/skills", {
        slug: newSkillSlug.value,
        content: newSkillContent.value,
      });
      cancelAddForm();
      await fetchSkills();
    } catch (err: any) {
      error.value = err.message || "Failed to create skill";
    } finally {
      adding.value = false;
    }
  }

  async function removeSkill(slug: string) {
    try {
      await apiDelete(`/skills/${slug}`);
      if (selectedSkill.value?.slug === slug) {
        selectedSkill.value = null;
        skillContent.value = "";
      }
      await fetchSkills();
    } catch (err: any) {
      error.value = err.message || "Failed to remove skill";
    }
  }

  async function viewSkill(skill: Skill) {
    selectedSkill.value = skill;
    editMode.value = false;
    loadingContent.value = true;
    try {
      const data = await apiGet(`/skills/${skill.slug}/content`);
      skillContent.value = data.content;
    } catch (err: any) {
      skillContent.value = `Error loading skill: ${err.message}`;
    } finally {
      loadingContent.value = false;
    }
  }

  function startEdit() {
    editContent.value = skillContent.value;
    editMode.value = true;
  }

  async function saveSkill() {
    if (!selectedSkill.value) return;
    try {
      await apiPut(`/skills/${selectedSkill.value.slug}/content`, { content: editContent.value });
      skillContent.value = editContent.value;
      editMode.value = false;
      await fetchSkills();
    } catch (err: any) {
      error.value = err.message || "Failed to save skill";
    }
  }

  // ---- Discovery functions ----

  async function loadDiscovery() {
    discoverLoading.value = true;
    discoverError.value = "";
    selectedDiscovered.value = null;
    previewContent.value = "";
    try {
      const params = new URLSearchParams({ source: discoverSource.value });
      if (discoverQuery.value.trim()) params.set("q", discoverQuery.value.trim());
      discoveredSkills.value = await apiGet(`/skills/discover?${params}`);
    } catch (err: any) {
      discoverError.value = err.message || "Failed to fetch community skills";
      discoveredSkills.value = [];
    } finally {
      discoverLoading.value = false;
    }
  }

  async function previewDiscovered(skill: DiscoveredSkill) {
    selectedDiscovered.value = skill;
    previewLoading.value = true;
    previewContent.value = "";
    try {
      const data = await apiGet(
        `/skills/preview?source=${skill.source}&slug=${encodeURIComponent(skill.slug)}`
      );
      previewContent.value = data.content;
    } catch (err: any) {
      previewContent.value = `Error loading preview: ${err.message}`;
    } finally {
      previewLoading.value = false;
    }
  }

  async function installDiscovered(skill: DiscoveredSkill) {
    installingSlug.value = skill.slug;
    error.value = "";
    try {
      await apiPost("/skills", { source: skill.source, slug: skill.slug });
      await fetchSkills();
      activeTab.value = "installed";
    } catch (err: any) {
      error.value = err.message || "Failed to install skill";
    } finally {
      installingSlug.value = "";
    }
  }

  function isInstalled(slug: string): boolean {
    return skills.value.some((s) => s.slug === slug);
  }

  function switchTab(tab: Tab) {
    activeTab.value = tab;
    selectedSkill.value = null;
    selectedDiscovered.value = null;
    skillContent.value = "";
    previewContent.value = "";
    if (tab === "discover" && discoveredSkills.value.length === 0) {
      loadDiscovery();
    }
  }

  onMounted(fetchSkills);
</script>

<template>
  <div class="flex h-full">
    <!-- Sidebar -->
    <div class="w-72 border-r border-border flex flex-col shrink-0">
      <!-- Tab switcher -->
      <div class="flex border-b border-border">
        <button
          @click="switchTab('installed')"
          class="flex-1 px-3 py-2 text-xs font-medium transition-colors"
          :class="
            activeTab === 'installed'
              ? 'border-b-2 border-primary text-primary'
              : 'text-muted-foreground hover:text-foreground'
          "
        >
          Installed
        </button>
        <button
          @click="switchTab('discover')"
          class="flex-1 px-3 py-2 text-xs font-medium transition-colors"
          :class="
            activeTab === 'discover'
              ? 'border-b-2 border-primary text-primary'
              : 'text-muted-foreground hover:text-foreground'
          "
        >
          <Globe class="w-3 h-3 inline mr-1" />
          Discover
        </button>
      </div>

      <!-- Installed tab content -->
      <template v-if="activeTab === 'installed'">
        <div class="p-3 border-b border-border space-y-2">
          <div class="flex gap-1">
            <button
              @click="openAddForm('git')"
              class="flex-1 flex items-center justify-center gap-1.5 px-2 py-1.5 text-xs rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
            >
              <Plus class="w-3.5 h-3.5" />
              From Git
            </button>
            <button
              @click="openAddForm('create')"
              class="flex-1 flex items-center justify-center gap-1.5 px-2 py-1.5 text-xs rounded-md border border-border hover:bg-accent"
            >
              <Plus class="w-3.5 h-3.5" />
              Create New
            </button>
          </div>

          <!-- Git clone form -->
          <div v-if="showAddForm && addMode === 'git'" class="space-y-1.5">
            <input
              v-model="newSkillUrl"
              type="text"
              placeholder="https://github.com/user/skill-repo.git"
              class="w-full rounded-md border border-input bg-background px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
              @keyup.enter="addSkillFromGit"
            />
            <div class="flex gap-1">
              <button
                @click="addSkillFromGit"
                :disabled="adding || !newSkillUrl.trim()"
                class="flex-1 px-2 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
              >
                {{ adding ? "Installing..." : "Install" }}
              </button>
              <button
                @click="cancelAddForm"
                class="px-2 py-1 text-xs rounded border border-border hover:bg-accent"
              >
                Cancel
              </button>
            </div>
          </div>

          <!-- Create new skill form -->
          <div v-if="showAddForm && addMode === 'create'" class="space-y-1.5">
            <div>
              <input
                v-model="newSkillTitle"
                type="text"
                placeholder="Skill title"
                class="w-full rounded-md border border-input bg-background px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
              />
              <p v-if="newSkillTitle.trim()" class="mt-0.5 text-xs text-muted-foreground font-mono">
                slug: {{ newSkillSlug }}
              </p>
            </div>
            <textarea
              v-model="newSkillContent"
              rows="8"
              placeholder="# My Skill&#10;&#10;Describe your skill in Markdown..."
              class="w-full rounded-md border border-input bg-background px-2 py-1.5 text-xs font-mono focus:outline-none focus:ring-1 focus:ring-ring resize-none"
            ></textarea>
            <div class="flex gap-1">
              <button
                @click="createSkill"
                :disabled="adding || !newSkillTitle.trim() || !newSkillContent.trim()"
                class="flex-1 px-2 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
              >
                {{ adding ? "Creating..." : "Create" }}
              </button>
              <button
                @click="cancelAddForm"
                class="px-2 py-1 text-xs rounded border border-border hover:bg-accent"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>

        <div class="flex-1 overflow-y-auto p-2">
          <div v-if="loading" class="text-xs text-muted-foreground p-2">Loading...</div>
          <div v-else-if="skills.length === 0" class="text-center py-8 text-muted-foreground">
            <Puzzle class="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p class="text-xs">No skills installed.</p>
          </div>
          <div
            v-for="skill in skills"
            :key="skill.slug"
            @click="viewSkill(skill)"
            class="flex items-center justify-between px-2 py-2 text-xs rounded cursor-pointer hover:bg-accent transition-colors group"
            :class="{ 'bg-accent font-medium': selectedSkill?.slug === skill.slug }"
          >
            <div class="min-w-0 flex-1">
              <div class="font-medium truncate">{{ skill.name }}</div>
              <div class="text-muted-foreground truncate">{{ skill.slug }}</div>
            </div>
            <button
              @click.stop="removeSkill(skill.slug)"
              class="opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-destructive/10 text-destructive transition-opacity shrink-0"
              title="Remove"
            >
              <Trash2 class="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </template>

      <!-- Discover tab content -->
      <template v-else>
        <div class="p-3 border-b border-border space-y-2">
          <!-- Source selector -->
          <select
            v-model="discoverSource"
            @change="loadDiscovery"
            class="w-full rounded-md border border-input bg-background px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
          >
            <option value="awesome-copilot">awesome-copilot</option>
            <option value="skillssh">skills.sh</option>
          </select>
          <!-- Search -->
          <div class="relative">
            <Search
              class="absolute left-2 top-1/2 -translate-y-1/2 w-3 h-3 text-muted-foreground"
            />
            <input
              v-model="discoverQuery"
              type="text"
              placeholder="Search skills..."
              class="w-full rounded-md border border-input bg-background pl-6 pr-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
              @keyup.enter="loadDiscovery"
            />
          </div>
          <button
            @click="loadDiscovery"
            :disabled="discoverLoading"
            class="w-full px-2 py-1.5 text-xs rounded-md bg-secondary text-secondary-foreground hover:bg-secondary/80 disabled:opacity-50"
          >
            {{ discoverLoading ? "Searching..." : "Search" }}
          </button>
        </div>

        <div class="flex-1 overflow-y-auto p-2">
          <div v-if="discoverLoading" class="text-xs text-muted-foreground p-2">Loading...</div>
          <div v-else-if="discoverError" class="text-xs text-destructive p-2">
            {{ discoverError }}
          </div>
          <div
            v-else-if="discoveredSkills.length === 0"
            class="text-center py-8 text-muted-foreground"
          >
            <Globe class="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p class="text-xs">No skills found.</p>
          </div>
          <div
            v-for="skill in discoveredSkills"
            :key="skill.slug"
            @click="previewDiscovered(skill)"
            class="flex items-start justify-between px-2 py-2 text-xs rounded cursor-pointer hover:bg-accent transition-colors gap-1"
            :class="{ 'bg-accent': selectedDiscovered?.slug === skill.slug }"
          >
            <div class="min-w-0 flex-1">
              <div class="font-medium truncate">{{ skill.slug }}</div>
              <div class="text-muted-foreground line-clamp-2 mt-0.5" :title="skill.description">
                {{ skill.description }}
              </div>
            </div>
            <button
              v-if="!isInstalled(skill.slug)"
              @click.stop="installDiscovered(skill)"
              :disabled="installingSlug === skill.slug"
              class="shrink-0 mt-0.5 px-1.5 py-0.5 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
              title="Install"
            >
              {{ installingSlug === skill.slug ? "..." : "Install" }}
            </button>
            <span
              v-else
              class="shrink-0 mt-0.5 px-1.5 py-0.5 text-xs rounded bg-muted text-muted-foreground"
            >
              Installed
            </span>
          </div>
        </div>
      </template>
    </div>

    <!-- Content panel -->
    <div class="flex-1 flex flex-col">
      <!-- Installed skill viewer -->
      <template v-if="activeTab === 'installed'">
        <div
          v-if="!selectedSkill"
          class="flex items-center justify-center h-full text-muted-foreground"
        >
          <div class="text-center">
            <Puzzle class="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p>Select a skill to view</p>
          </div>
        </div>

        <template v-else>
          <div class="flex items-center justify-between px-4 py-2 border-b border-border">
            <div>
              <span class="text-sm font-medium">{{ selectedSkill.name }}</span>
              <span class="text-xs text-muted-foreground ml-2 font-mono"
                >{{ selectedSkill.slug }}/SKILL.md</span
              >
            </div>
            <div class="flex gap-1">
              <template v-if="!editMode">
                <button
                  @click="startEdit"
                  class="p-1.5 rounded hover:bg-accent text-muted-foreground"
                  title="Edit"
                >
                  <Pencil class="w-4 h-4" />
                </button>
              </template>
              <template v-else>
                <button
                  @click="saveSkill"
                  class="p-1.5 rounded hover:bg-accent text-green-500"
                  title="Save"
                >
                  <Save class="w-4 h-4" />
                </button>
                <button
                  @click="editMode = false"
                  class="p-1.5 rounded hover:bg-accent text-muted-foreground"
                  title="Cancel"
                >
                  <X class="w-4 h-4" />
                </button>
              </template>
            </div>
          </div>

          <div class="flex-1 overflow-y-auto p-4">
            <div v-if="loadingContent" class="text-muted-foreground text-sm">Loading...</div>
            <textarea
              v-else-if="editMode"
              v-model="editContent"
              class="w-full h-full min-h-[400px] font-mono text-sm bg-background border border-input rounded-md p-3 focus:outline-none focus:ring-1 focus:ring-ring resize-none"
            ></textarea>
            <div v-else class="space-y-4">
              <div
                v-if="Object.keys(installedSkillContent.frontmatter).length > 0"
                class="rounded-lg border border-border bg-card p-4"
              >
                <div class="flex items-center justify-between">
                  <p class="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                    Metadata
                  </p>
                </div>
                <dl class="mt-3 grid gap-2 sm:grid-cols-2">
                  <div
                    v-for="[key, value] in Object.entries(installedSkillContent.frontmatter)"
                    :key="key"
                    class="rounded-md bg-muted px-3 py-2"
                  >
                    <dt class="text-[10px] uppercase tracking-wide text-muted-foreground">
                      {{ key }}
                    </dt>
                    <dd class="mt-1 text-sm text-foreground">
                      {{ Array.isArray(value) ? value.join(", ") : String(value) }}
                    </dd>
                  </div>
                </dl>
              </div>
              <MarkdownContent :content="installedSkillContent.body" />
            </div>
          </div>
        </template>
      </template>

      <!-- Discovery preview -->
      <template v-else>
        <div
          v-if="!selectedDiscovered"
          class="flex items-center justify-center h-full text-muted-foreground"
        >
          <div class="text-center">
            <Globe class="w-12 h-12 mx-auto mb-3 opacity-50" />
            <p>Select a skill to preview</p>
          </div>
        </div>

        <template v-else>
          <div class="flex items-center justify-between px-4 py-2 border-b border-border">
            <div class="min-w-0 flex-1">
              <span class="text-sm font-medium">{{ selectedDiscovered.slug }}</span>
              <span class="text-xs text-muted-foreground ml-2">{{
                selectedDiscovered.source
              }}</span>
            </div>
            <button
              v-if="!isInstalled(selectedDiscovered.slug)"
              @click="installDiscovered(selectedDiscovered)"
              :disabled="installingSlug === selectedDiscovered.slug"
              class="ml-2 shrink-0 px-3 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
            >
              {{ installingSlug === selectedDiscovered.slug ? "Installing..." : "Install" }}
            </button>
            <span
              v-else
              class="ml-2 shrink-0 px-3 py-1 text-xs rounded bg-muted text-muted-foreground"
            >
              Installed
            </span>
          </div>

          <div class="flex-1 overflow-y-auto p-4">
            <div v-if="previewLoading" class="text-muted-foreground text-sm">
              Loading preview...
            </div>
            <div v-else class="space-y-4">
              <div
                v-if="Object.keys(previewSkillContent.frontmatter).length > 0"
                class="rounded-lg border border-border bg-card p-4"
              >
                <div class="flex items-center justify-between">
                  <p class="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                    Metadata
                  </p>
                </div>
                <dl class="mt-3 grid gap-2 sm:grid-cols-2">
                  <div
                    v-for="[key, value] in Object.entries(previewSkillContent.frontmatter)"
                    :key="key"
                    class="rounded-md bg-muted px-3 py-2"
                  >
                    <dt class="text-[10px] uppercase tracking-wide text-muted-foreground">
                      {{ key }}
                    </dt>
                    <dd class="mt-1 text-sm text-foreground">
                      {{ Array.isArray(value) ? value.join(", ") : String(value) }}
                    </dd>
                  </div>
                </dl>
              </div>
              <MarkdownContent :content="previewSkillContent.body" />
            </div>
          </div>
        </template>
      </template>
    </div>

    <p
      v-if="error"
      class="absolute bottom-4 left-4 text-sm text-destructive bg-background border border-destructive/30 px-3 py-2 rounded-md"
    >
      {{ error }}
    </p>
  </div>
</template>
