// packages/web/src/views/WikiView.tsx
import { api } from '@/lib/api';
import { BookOpen, FileText, Plus, Save } from 'lucide-react';
import { marked } from 'marked';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';

interface WikiPage {
	name: string;
	path: string;
}

export function WikiView() {
	const [scope, setScope] = useState('shared');
	const [pages, setPages] = useState<WikiPage[]>([]);
	const [selectedPage, setSelectedPage] = useState<string | null>(null);
	const [content, setContent] = useState('');
	const [editing, setEditing] = useState(false);
	const [editContent, setEditContent] = useState('');
	const [creating, setCreating] = useState(false);
	const [newPageName, setNewPageName] = useState('');

	useEffect(() => {
		loadPages();
	}, [scope]);

	function loadPages() {
		api
			.get<{ scope: string; pages: WikiPage[] }>(`/wiki/${scope}`)
			.then((d) => setPages(d.pages))
			.catch(() => setPages([]));
	}

	async function loadPage(name: string) {
		try {
			const data = await api.get<{ content: string }>(`/wiki/${scope}/${name}`);
			setContent(data.content);
			setSelectedPage(name);
			setEditing(false);
		} catch {
			toast.error('Failed to load page');
		}
	}

	async function savePage() {
		if (!selectedPage) return;
		try {
			await api.put(`/wiki/${scope}/${selectedPage}`, { content: editContent });
			setContent(editContent);
			setEditing(false);
			toast.success('Page saved');
		} catch {
			toast.error('Failed to save');
		}
	}

	async function createPage() {
		if (!newPageName.trim()) return;
		try {
			await api.put(`/wiki/${scope}/${newPageName}`, { content: `# ${newPageName}\n\n` });
			toast.success('Page created');
			setCreating(false);
			setNewPageName('');
			loadPages();
			loadPage(newPageName);
		} catch {
			toast.error('Failed to create page');
		}
	}

	return (
		<div className="flex h-full">
			{/* Sidebar */}
			<div className="w-64 border-r border-[var(--color-border)] flex flex-col h-full">
				<header className="h-14 flex items-center px-4 border-b border-[var(--color-border)] shrink-0">
					<h1 className="text-lg font-semibold gradient-text">Wiki</h1>
				</header>

				{/* Scope selector */}
				<div className="flex gap-1 p-2 border-b border-[var(--color-border)]">
					{['io', 'shared'].map((s) => (
						<button
							key={s}
							type="button"
							onClick={() => {
								setScope(s);
								setSelectedPage(null);
							}}
							className={`px-2 py-1 rounded text-xs ${
								scope === s
									? 'bg-white/10 text-[var(--color-foreground)]'
									: 'text-[var(--color-muted-foreground)]'
							}`}
						>
							{s}
						</button>
					))}
				</div>

				{/* Pages */}
				<div className="flex-1 overflow-y-auto p-2">
					{pages.map((page) => (
						<button
							key={page.name}
							type="button"
							onClick={() => loadPage(page.name)}
							className={`w-full text-left px-3 py-2 rounded-md text-sm flex items-center gap-2 transition-colors ${
								selectedPage === page.name ? 'bg-white/10' : 'hover:bg-white/5'
							}`}
						>
							<FileText size={14} className="text-[var(--color-muted-foreground)]" />
							{page.name}
						</button>
					))}
				</div>

				{/* Create page */}
				<div className="p-2 border-t border-[var(--color-border)]">
					{creating ? (
						<div className="flex gap-1">
							<input
								type="text"
								value={newPageName}
								onChange={(e) => setNewPageName(e.target.value)}
								placeholder="page-name"
								className="flex-1 px-2 py-1 rounded text-xs bg-[var(--color-input)] border border-[var(--color-border)] outline-none"
								onKeyDown={(e) => e.key === 'Enter' && createPage()}
							/>
							<button
								type="button"
								onClick={createPage}
								className="px-2 py-1 rounded text-xs bg-[var(--color-accent)] text-white"
							>
								OK
							</button>
						</div>
					) : (
						<button
							type="button"
							onClick={() => setCreating(true)}
							className="w-full flex items-center gap-2 px-3 py-2 rounded-md text-xs text-[var(--color-muted-foreground)] hover:bg-white/5"
						>
							<Plus size={14} /> New page
						</button>
					)}
				</div>
			</div>

			{/* Content */}
			<div className="flex-1 flex flex-col overflow-hidden">
				{selectedPage ? (
					<>
						<div className="h-14 flex items-center px-6 border-b border-[var(--color-border)] justify-between shrink-0">
							<h2 className="font-semibold">{selectedPage}</h2>
							<div className="flex gap-2">
								{editing ? (
									<button
										type="button"
										onClick={savePage}
										className="flex items-center gap-1 px-3 py-1.5 rounded-md bg-[var(--color-accent)] text-white text-xs"
									>
										<Save size={12} /> Save
									</button>
								) : (
									<button
										type="button"
										onClick={() => {
											setEditing(true);
											setEditContent(content);
										}}
										className="px-3 py-1.5 rounded-md bg-white/5 text-xs hover:bg-white/10"
									>
										Edit
									</button>
								)}
							</div>
						</div>
						<div className="flex-1 overflow-y-auto p-6">
							{editing ? (
								<textarea
									value={editContent}
									onChange={(e) => setEditContent(e.target.value)}
									className="w-full h-full bg-transparent font-mono text-sm outline-none resize-none"
								/>
							) : (
								<div
									className="prose-io"
									// biome-ignore lint: markdown rendering
									dangerouslySetInnerHTML={{ __html: marked.parse(content) as string }}
								/>
							)}
						</div>
					</>
				) : (
					<div className="h-full flex items-center justify-center text-[var(--color-muted-foreground)]">
						<div className="text-center">
							<BookOpen size={48} className="mx-auto mb-3 opacity-30" />
							<p>Select a page to view</p>
						</div>
					</div>
				)}
			</div>
		</div>
	);
}

// web/src/views/WikiView.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { apiGet, apiPut, apiDelete } from "@/lib/api";
import { BookOpen, Search, Plus, Pencil, Trash2, Save, X, Link } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";
import WikiTree from "@/components/WikiTree.vue";

const pages = ref<string[]>([]);
const selectedPage = ref<string | null>(null);
const pageContent = ref("");
const editMode = ref(false);
const editContent = ref("");
const searchQuery = ref("");
const loading = ref(true);
const showNewForm = ref(false);
const newPagePath = ref("");
const backlinks = ref<string[]>([]);

onMounted(async () => {
  try {
    pages.value = await apiGet("/wiki/pages");
  } finally {
    loading.value = false;
  }
});

async function selectPage(path: string) {
  selectedPage.value = path;
  editMode.value = false;
  const data = await apiGet(`/wiki/page/${path}`);
  pageContent.value = data.content;
  backlinks.value = await apiGet(`/wiki/backlinks/${path}`);
}

function startEdit() {
  editContent.value = pageContent.value;
  editMode.value = true;
}

async function savePage() {
  if (!selectedPage.value) return;
  await apiPut(`/wiki/page/${selectedPage.value}`, { content: editContent.value });
  pageContent.value = editContent.value;
  editMode.value = false;
  backlinks.value = await apiGet(`/wiki/backlinks/${selectedPage.value}`);
}

async function deletePage() {
  if (!selectedPage.value) return;
  if (!confirm(`Delete "${selectedPage.value}"?`)) return;
  await apiDelete(`/wiki/page/${selectedPage.value}`);
  pages.value = pages.value.filter((p) => p !== selectedPage.value);
  selectedPage.value = null;
  pageContent.value = "";
  backlinks.value = [];
}

async function createPage() {
  const path = newPagePath.value.trim();
  if (!path) return;
  // Ensure .md extension
  const fullPath = path.endsWith(".md") ? path : `${path}.md`;
  await apiPut(`/wiki/page/${fullPath}`, { content: "" });
  if (!pages.value.includes(fullPath)) {
    pages.value.push(fullPath);
    pages.value.sort();
  }
  showNewForm.value = false;
  newPagePath.value = "";
  // Open the new page in edit mode
  selectedPage.value = fullPath;
  pageContent.value = "";
  editContent.value = "";
  editMode.value = true;
  backlinks.value = [];
}

</script>

<template>
  <div class="flex h-full">
    <!-- Sidebar file tree -->
    <div class="w-64 border-r border-border flex flex-col shrink-0">
      <div class="p-3 border-b border-border space-y-2">
        <div class="relative">
          <Search class="absolute left-2.5 top-2.5 w-3.5 h-3.5 text-muted-foreground" />
          <input
            v-model="searchQuery"
            placeholder="Search pages..."
            class="w-full rounded-md border border-input bg-background pl-8 pr-3 py-2 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
          />
        </div>
        <button
          @click="showNewForm = !showNewForm"
          class="w-full flex items-center justify-center gap-1.5 px-2 py-1.5 text-xs rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
        >
          <Plus class="w-3.5 h-3.5" />
          New Page
        </button>
        <div v-if="showNewForm" class="space-y-1.5">
          <input
            v-model="newPagePath"
            placeholder="path/to/page.md"
            class="w-full rounded-md border border-input bg-background px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
            @keyup.enter="createPage"
          />
          <div class="flex gap-1">
            <button
              @click="createPage"
              :disabled="!newPagePath.trim()"
              class="flex-1 px-2 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
            >
              Create
            </button>
            <button
              @click="showNewForm = false; newPagePath = ''"
              class="px-2 py-1 text-xs rounded border border-border hover:bg-accent"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
      <div class="flex-1 overflow-y-auto p-2">
        <div v-if="loading" class="text-xs text-muted-foreground p-2">Loading...</div>
        <WikiTree
          v-else
          :pages="pages"
          :selected-page="selectedPage"
          :search-query="searchQuery"
          @select="selectPage($event)"
        />
      </div>
    </div>

    <!-- Content -->
    <div class="flex-1 flex flex-col">
      <div v-if="!selectedPage" class="flex items-center justify-center h-full text-muted-foreground">
        <div class="text-center">
          <BookOpen class="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p>Select a page to view</p>
        </div>
      </div>

      <template v-else>
        <!-- Toolbar -->
        <div class="flex items-center justify-between px-4 py-2 border-b border-border">
          <span class="text-sm font-medium font-mono">{{ selectedPage }}</span>
          <div class="flex gap-1">
            <template v-if="!editMode">
              <button @click="startEdit" class="p-1.5 rounded hover:bg-accent text-muted-foreground" title="Edit">
                <Pencil class="w-4 h-4" />
              </button>
              <button @click="deletePage" class="p-1.5 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive" title="Delete">
                <Trash2 class="w-4 h-4" />
              </button>
            </template>
            <template v-else>
              <button @click="savePage" class="p-1.5 rounded hover:bg-accent text-green-500" title="Save">
                <Save class="w-4 h-4" />
              </button>
              <button @click="editMode = false" class="p-1.5 rounded hover:bg-accent text-muted-foreground" title="Cancel">
                <X class="w-4 h-4" />
              </button>
            </template>
          </div>
        </div>

        <!-- Content area -->
        <div class="flex-1 overflow-y-auto p-4">
          <textarea
            v-if="editMode"
            v-model="editContent"
            class="w-full h-full min-h-[400px] font-mono text-sm bg-background border border-input rounded-md p-3 focus:outline-none focus:ring-1 focus:ring-ring resize-none"
          ></textarea>
          <template v-else>
            <MarkdownContent :content="pageContent" />
            <div v-if="backlinks.length > 0" class="mt-8 pt-4 border-t border-border">
              <div class="flex items-center gap-1.5 mb-2 text-xs font-medium text-muted-foreground">
                <Link class="w-3.5 h-3.5" />
                Backlinks
              </div>
              <ul class="space-y-1">
                <li v-for="link in backlinks" :key="link">
                  <button
                    @click="selectPage(link)"
                    class="text-xs text-primary hover:underline font-mono"
                  >{{ link }}</button>
                </li>
              </ul>
            </div>
          </template>
        </div>
      </template>
    </div>
  </div>
</template>
