// web/src/views/ChatView.vue
<script setup lang="ts">
import { computed, ref, nextTick, onMounted, watch } from "vue";
import { useChatStore } from "@/stores/chat";
import { Send, Square, Paperclip, X, Image as ImageIcon, FileText } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";
import LogoIcon from "@/components/LogoIcon.vue";
import {
  fileToMessageAttachment,
  formatAttachmentSize,
  isImageAttachment,
  MAX_ATTACHMENT_BYTES,
  MAX_TOTAL_ATTACHMENT_BYTES,
  toDataUrl,
  type MessageAttachment,
  validateAttachmentSizes,
} from "@/lib/attachments";

const chat = useChatStore();
const input = ref("");
const composerError = ref("");
const messagesContainer = ref<HTMLElement>();
const fileInput = ref<HTMLInputElement>();
const pendingAttachments = ref<MessageAttachment[]>([]);
const textareaRef = ref<HTMLTextAreaElement>();
const isDragging = ref(false);

const totalPendingAttachmentBytes = computed(() =>
  pendingAttachments.value.reduce((sum, attachment) => sum + attachment.size, 0)
);

const canSend = computed(
  () =>
    !chat.isStreaming &&
    (input.value.trim().length > 0 || pendingAttachments.value.length > 0)
);

async function queueAttachments(files: FileList | null): Promise<void> {
  if (!files || files.length === 0) return;

  composerError.value = "";
  const parsed: MessageAttachment[] = [];

  try {
    for (const file of Array.from(files)) {
      parsed.push(await fileToMessageAttachment(file));
    }
  } catch (err: any) {
    composerError.value = err?.message ?? "Unable to read one or more files.";
    return;
  }

  const next = [...pendingAttachments.value, ...parsed];
  const validation = validateAttachmentSizes(next);
  if (!validation.ok) {
    composerError.value = validation.error;
    return;
  }

  pendingAttachments.value = next;
  if (fileInput.value) fileInput.value.value = "";
}

function removeAttachment(index: number): void {
  pendingAttachments.value.splice(index, 1);
  composerError.value = "";
}

function openPicker(): void {
  fileInput.value?.click();
}

function handleFileInput(event: Event): void {
  const target = event.target as HTMLInputElement | null;
  void queueAttachments(target?.files ?? null);
}

async function send() {
  if (!canSend.value) return;

  const text = input.value.trim();
  const attachments = [...pendingAttachments.value];
  const prompt = text || "Please review the attached file(s).";

  input.value = "";
  pendingAttachments.value = [];
  composerError.value = "";

  await chat.sendMessage(prompt, attachments);
}

function scrollToBottom() {
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
  }
}

function updateComposerHeight(): void {
  if (!textareaRef.value) return;
  textareaRef.value.style.height = "auto";
  textareaRef.value.style.height = `${Math.min(textareaRef.value.scrollHeight, 120)}px`;
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "Enter" && !e.shiftKey) {
    e.preventDefault();
    send();
  }
}

function onDragOver(event: DragEvent): void {
  event.preventDefault();
  isDragging.value = true;
}

function onDragLeave(event: DragEvent): void {
  event.preventDefault();
  isDragging.value = false;
}

async function onDrop(event: DragEvent): Promise<void> {
  event.preventDefault();
  isDragging.value = false;
  await queueAttachments(event.dataTransfer?.files ?? null);
}

// Auto-scroll whenever messages change (new message, streaming content updates)
watch(
  () => chat.messages.map((m) => m.content),
  async () => {
    await nextTick();
    scrollToBottom();
  },
  { deep: true }
);

watch(
  () => chat.messages.length,
  async () => {
    await nextTick();
    scrollToBottom();
  }
);

watch(
  () => input.value,
  async () => {
    await nextTick();
    updateComposerHeight();
  }
);

onMounted(() => {
  updateComposerHeight();
  scrollToBottom();
});
</script>

<template>
  <div class="flex flex-col h-full">
    <!-- Messages -->
    <div ref="messagesContainer" class="flex-1 overflow-y-auto p-4 space-y-4">
      <div v-if="chat.messages.length === 0" class="flex items-center justify-center h-full">
        <div class="text-center text-muted-foreground">
          <LogoIcon :size="56" class="mx-auto mb-4" />
          <p class="text-lg font-medium">Welcome to IO</p>
          <p class="text-sm mt-1">Send a message to get started.</p>
        </div>
      </div>

      <div
        v-for="msg in chat.messages"
        :key="msg.id"
        class="flex"
        :class="msg.role === 'user' ? 'justify-end' : 'justify-start'"
      >
        <div
          class="max-w-[75%] rounded-lg px-4 py-2 text-sm"
          :class="
            msg.role === 'user'
              ? 'bg-primary text-primary-foreground'
              : 'bg-muted text-foreground'
          "
        >
          <div v-if="msg.attachments.length > 0" class="mb-2 space-y-2">
            <div
              v-for="(attachment, idx) in msg.attachments"
              :key="`${msg.id}-${idx}`"
              class="rounded border border-border/50 p-2 bg-background/70 text-foreground"
            >
              <img
                v-if="isImageAttachment(attachment)"
                :src="toDataUrl(attachment)"
                :alt="attachment.name"
                class="max-h-44 rounded mb-1 object-contain"
              />
              <div class="flex items-center gap-2 text-xs">
                <ImageIcon v-if="isImageAttachment(attachment)" class="w-3.5 h-3.5" />
                <FileText v-else class="w-3.5 h-3.5" />
                <span class="truncate">{{ attachment.name }}</span>
                <span class="opacity-70">{{ formatAttachmentSize(attachment.size) }}</span>
              </div>
            </div>
          </div>
          <MarkdownContent v-if="msg.content" :content="msg.content" :class="msg.role === 'user' ? 'prose-invert' : ''" />
          <span v-else-if="!msg.streaming" class="text-muted-foreground">...</span>
          <div
            v-if="msg.streaming"
            class="inline-block w-2 h-4 bg-current animate-pulse ml-1"
          ></div>
        </div>
      </div>
    </div>

    <!-- Input -->
    <div
      class="border-t border-border p-4"
      :class="isDragging ? 'bg-accent/40' : ''"
      @dragover="onDragOver"
      @dragleave="onDragLeave"
      @drop="onDrop"
    >
      <input
        ref="fileInput"
        type="file"
        multiple
        class="hidden"
        @change="handleFileInput"
      />

      <div v-if="pendingAttachments.length > 0" class="mb-2 space-y-2">
        <div class="flex flex-wrap gap-2">
          <div
            v-for="(attachment, idx) in pendingAttachments"
            :key="`${attachment.name}-${idx}`"
            class="flex items-center gap-2 rounded border border-border px-2 py-1 text-xs bg-muted"
          >
            <ImageIcon v-if="isImageAttachment(attachment)" class="w-3.5 h-3.5" />
            <FileText v-else class="w-3.5 h-3.5" />
            <span class="max-w-[170px] truncate">{{ attachment.name }}</span>
            <span class="opacity-70">{{ formatAttachmentSize(attachment.size) }}</span>
            <button class="hover:text-destructive" @click="removeAttachment(idx)">
              <X class="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
        <p class="text-xs text-muted-foreground">
          {{ formatAttachmentSize(totalPendingAttachmentBytes) }} attached · Max per file {{ formatAttachmentSize(MAX_ATTACHMENT_BYTES) }} · Max total {{ formatAttachmentSize(MAX_TOTAL_ATTACHMENT_BYTES) }}
        </p>
      </div>

      <p v-if="composerError" class="text-xs text-destructive mb-2">{{ composerError }}</p>

      <div class="flex gap-2 items-end">
        <button
          class="rounded-md border border-input p-2 hover:bg-accent disabled:opacity-50"
          :disabled="chat.isStreaming"
          @click="openPicker"
          title="Attach files"
        >
          <Paperclip class="w-4 h-4" />
        </button>
        <textarea
          ref="textareaRef"
          v-model="input"
          @keydown="handleKeydown"
          placeholder="Send a message..."
          rows="1"
          class="flex-1 resize-none rounded-md border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring min-h-[40px] max-h-[120px]"
        ></textarea>
        <button
          @click="send"
          :disabled="!canSend"
          class="rounded-md bg-primary text-primary-foreground p-2 hover:bg-primary/90 disabled:opacity-50 transition-colors"
        >
          <Send v-if="!chat.isStreaming" class="w-4 h-4" />
          <Square v-else class="w-4 h-4" />
        </button>
      </div>
    </div>
  </div>
</template>

// packages/web/src/views/ChatView.tsx
import { IoMark } from "@/components/ui/io-mark";
import { configuredMarked as marked } from "@/components/ui/markdown";
import { Chip } from "@/components/ui/shared";
import { useChat } from "@/hooks/use-chat";
import { useTimezone } from "@/hooks/use-config";
import { useAuth } from "@/lib/auth";
import { formatTime as fmtTime } from "@/lib/timezone";
import { Activity, ChevronDown, Paperclip, Send, Square } from "lucide-react";
import { useLayoutEffect, useRef, useState } from "react";

export function ChatView() {
	const { session } = useAuth();
	const timezone = useTimezone();
	const {
		messages,
		streaming,
		isStreaming,
		isThinking,
		sendChatMessage,
		stopStreaming,
		addUserMessage,
		uploadAttachment,
	} = useChat();
	const [input, setInput] = useState("");
	const [selectedFile, setSelectedFile] = useState<File | null>(null);
	const [expandedTool, setExpandedTool] = useState<string | null>(null);
	const messagesContainerRef = useRef<HTMLDivElement>(null);
	const textareaRef = useRef<HTMLTextAreaElement>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);

	useLayoutEffect(() => {
		const container = messagesContainerRef.current;
		if (container) {
			container.scrollTop = container.scrollHeight;
		}
	}, [messages, streaming, isThinking]);

	async function handleSend() {
		const text = input.trim();
		if ((!text && !selectedFile) || isStreaming || isThinking) return;

		const messageId = crypto.randomUUID();
		const attachmentName = selectedFile?.name;
		const outboundContent = [text, attachmentName ? `Attachment: ${attachmentName}` : ""]
			.filter(Boolean)
			.join("\n\n");

		addUserMessage({
			id: messageId,
			role: "user",
			content: text,
			timestamp: new Date().toISOString(),
			attachmentName,
		});
		setInput("");
		setSelectedFile(null);
		if (fileInputRef.current) fileInputRef.current.value = "";
		if (textareaRef.current) textareaRef.current.style.height = "auto";

		try {
			if (selectedFile) {
				await uploadAttachment(selectedFile, messageId);
			}
			await sendChatMessage(outboundContent);
		} catch {
			// handled by context
		}
	}

	function handleKeyDown(e: React.KeyboardEvent) {
		if (e.key === "Enter" && !e.shiftKey) {
			e.preventDefault();
			handleSend();
		}
	}

	function handleInput(e: React.ChangeEvent<HTMLTextAreaElement>) {
		setInput(e.target.value);
		if (textareaRef.current) {
			textareaRef.current.style.height = "auto";
			textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 160)}px`;
		}
	}

	return (
		<div className="flex flex-col flex-1 min-h-0">
			{/* Messages */}
			<div ref={messagesContainerRef} className="flex-1 overflow-y-auto px-5 py-5 space-y-5">
				{messages.map((msg) => (
					<div
						key={msg.id}
						className={`flex gap-3 ${msg.role === "user" ? "flex-row-reverse" : ""}`}
					>
						{/* Avatar */}
						<div
							className={`flex-shrink-0 w-6 h-6 rounded-lg flex items-center justify-center text-[10px] font-mono mt-0.5 ${
								msg.role === "user"
									? "border border-[#E43A9C]/30 text-[#E43A9C]"
									: "bg-[#282828] border border-white/[0.07] text-zinc-500"
							}`}
							style={msg.role === "user" ? { background: "rgba(228,58,156,0.12)" } : undefined}
						>
							{msg.role === "user" ? (
								(session?.user?.email?.charAt(0).toUpperCase() ?? "U")
							) : (
								<IoMark height={12} />
							)}
						</div>

						{/* Content */}
						<div
							className={`flex flex-col gap-1.5 max-w-[72%] ${msg.role === "user" ? "items-end" : "items-start"}`}
						>
							{/* Tool call card */}
							{msg.toolCall && (
								<button
									type="button"
									onClick={() => setExpandedTool(expandedTool === msg.id ? null : msg.id)}
									className="w-full text-left border border-white/[0.07] bg-[#1e1e1e] rounded-xl px-3 py-2 flex items-center gap-2 hover:border-[#E43A9C]/25 transition-colors"
								>
									<Activity className="w-3 h-3 text-[#E43A9C] flex-shrink-0" />
									<span className="text-[11px] font-mono text-zinc-400 flex-1">
										{msg.toolCall.name}
									</span>
									<Chip
										variant={
											msg.toolCall.status === "done"
												? "success"
												: msg.toolCall.status === "error"
													? "error"
													: "warning"
										}
									>
										{msg.toolCall.status}
									</Chip>
									<ChevronDown
										className={`w-3 h-3 text-zinc-600 transition-transform flex-shrink-0 ${expandedTool === msg.id ? "rotate-180" : ""}`}
									/>
								</button>
							)}
							{msg.toolCall && expandedTool === msg.id && (
								<div className="w-full bg-[#181818] border border-white/[0.06] rounded-xl px-3 py-2">
									<p className="text-[11px] font-mono text-zinc-500">{msg.toolCall.result}</p>
								</div>
							)}

							{msg.attachmentName && (
								<div className="rounded-xl border border-white/[0.08] bg-[#1e1e1e] px-3 py-2 text-[11px] font-mono text-zinc-400">
									{msg.attachmentName}
								</div>
							)}

							{/* Message bubble */}
							{msg.content && (
								<div
									className={`rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
										msg.role === "user"
											? "text-white rounded-tr-sm"
											: "bg-[#222222] border border-white/[0.07] text-zinc-200 rounded-tl-sm"
									}`}
									style={
										msg.role === "user"
											? { background: "linear-gradient(135deg, #D83333 0%, #C0285E 100%)" }
											: undefined
									}
								>
									{msg.role === "user" ? (
										<p className="whitespace-pre-wrap">{msg.content}</p>
									) : (
										<div
											className="prose-io"
											// biome-ignore lint: markdown rendering
											dangerouslySetInnerHTML={{ __html: marked.parse(msg.content) as string }}
										/>
									)}
								</div>
							)}

							{/* Timestamp */}
							<span className="text-[11px] text-zinc-700 font-mono px-0.5">
								{fmtTime(msg.timestamp, timezone)}
							</span>
						</div>
					</div>
				))}

				{/* Thinking indicator */}
				{isThinking && (
					<div className="flex gap-3">
						<div className="flex-shrink-0 w-6 h-6 rounded-lg flex items-center justify-center bg-[#282828] border border-white/[0.07] mt-0.5">
							<IoMark height={12} />
						</div>
						<div className="bg-[#222222] border border-white/[0.07] rounded-2xl rounded-tl-sm px-4 py-3 flex items-center gap-1.5">
							{[0, 120, 240].map((d) => (
								<span
									key={d}
									className="w-1.5 h-1.5 rounded-full bg-[#E43A9C] animate-bounce"
									style={{ animationDelay: `${d}ms` }}
								/>
							))}
						</div>
					</div>
				)}

				{/* Streaming indicator */}
				{isStreaming && streaming && (
					<div className="flex gap-3">
						<div className="flex-shrink-0 w-6 h-6 rounded-lg flex items-center justify-center bg-[#282828] border border-white/[0.07] mt-0.5">
							<IoMark height={12} />
						</div>
						<div className="bg-[#222222] border border-white/[0.07] rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[72%]">
							<div
								className="prose-io text-sm"
								// biome-ignore lint: streaming markdown
								dangerouslySetInnerHTML={{ __html: marked.parse(streaming) as string }}
							/>
						</div>
					</div>
				)}

				{/* Streaming dots (no content yet) */}
				{isStreaming && !streaming && (
					<div className="flex gap-3">
						<div className="flex-shrink-0 w-6 h-6 rounded-lg flex items-center justify-center bg-[#282828] border border-white/[0.07] mt-0.5">
							<IoMark height={12} />
						</div>
						<div className="bg-[#222222] border border-white/[0.07] rounded-2xl rounded-tl-sm px-4 py-3 flex items-center gap-1.5">
							{[0, 120, 240].map((d) => (
								<span
									key={d}
									className="w-1.5 h-1.5 rounded-full bg-[#E43A9C] animate-bounce"
									style={{ animationDelay: `${d}ms` }}
								/>
							))}
						</div>
					</div>
				)}
			</div>

			{/* Input area */}
			<div className="border-t border-white/[0.06] p-4 flex-shrink-0">
				<div className="bg-[#1e1e1e] border border-white/[0.08] rounded-2xl overflow-hidden transition-colors focus-within:border-[#E43A9C]/30">
					<input
						ref={fileInputRef}
						type="file"
						className="hidden"
						onChange={(e) => setSelectedFile(e.target.files?.[0] ?? null)}
					/>
					{selectedFile && (
						<div className="px-4 pt-3 text-[11px] font-mono text-zinc-400">
							Attached: {selectedFile.name}
						</div>
					)}
					<textarea
						ref={textareaRef}
						value={input}
						onChange={handleInput}
						onKeyDown={handleKeyDown}
						placeholder="Message IO…"
						rows={1}
						className="w-full bg-transparent px-4 pt-3 pb-1 text-sm text-zinc-200 placeholder:text-zinc-700 resize-none focus:outline-none"
						style={{ minHeight: "42px", maxHeight: "160px", fontFamily: "Inter, sans-serif" }}
					/>
					<div className="flex items-center justify-between px-3 pb-2.5">
						<button
							type="button"
							onClick={() => fileInputRef.current?.click()}
							className="p-1.5 rounded-lg hover:bg-white/[0.05] text-zinc-700 hover:text-zinc-400 transition-colors"
						>
							<Paperclip className="w-4 h-4" />
						</button>
						<div className="flex items-center gap-2">
							{isStreaming ? (
								<button
									type="button"
									onClick={() => stopStreaming()}
									className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-[11px] font-mono text-zinc-300 transition-colors"
								>
									<Square className="w-3 h-3" /> Stop
								</button>
							) : (
								<button
									type="button"
									onClick={handleSend}
									disabled={(!input.trim() && !selectedFile) || isThinking}
									className="p-2 rounded-xl text-white disabled:opacity-30 disabled:cursor-not-allowed transition-opacity hover:opacity-90"
									style={{ background: "linear-gradient(135deg, #D83333, #E43A9C)" }}
								>
									<Send className="w-3.5 h-3.5" />
								</button>
							)}
						</div>
					</div>
				</div>
				<p className="text-center text-[11px] text-zinc-800 font-mono mt-2">
					IO may make mistakes. Verify important outputs.
				</p>
			</div>
		</div>
	);
}
