// web/src/views/FeedView.vue
<script setup lang="ts">
import { ref, onMounted, computed } from "vue";
import { apiGet, apiPost, apiDelete } from "@/lib/api";
import { Inbox, Check, Trash2 } from "lucide-vue-next";
import MarkdownContent from "@/components/MarkdownContent.vue";
import { getSquadLabelStyle } from "@/lib/squad-colors";

interface FeedItem {
  id: string;
  source: string;
  title: string;
  content: string;
  read: number;
  created_at: string;
}

interface Squad {
  id: string;
  name: string;
  color: string;
}

const items = ref<FeedItem[]>([]);
const squads = ref<Squad[]>([]);
const unreadCount = ref(0);
const filter = ref<"all" | "unread">("all");
const loading = ref(true);
const expandedId = ref<string | null>(null);

async function loadFeed() {
  loading.value = true;
  try {
    const data = await apiGet(`/feed?unread=${filter.value === "unread"}`);
    items.value = data.items;
    unreadCount.value = data.unreadCount;
  } finally {
    loading.value = false;
  }
}

async function loadSquads() {
  const data = await apiGet("/squads");
  squads.value = data.squads;
}

async function markRead(id: string) {
  await apiPost(`/feed/${id}/read`);
  const item = items.value.find((i) => i.id === id);
  if (item) {
    item.read = 1;
    unreadCount.value = Math.max(0, unreadCount.value - 1);
  }
}

async function deleteItem(id: string) {
  await apiDelete(`/feed/${id}`);
  items.value = items.value.filter((i) => i.id !== id);
}

function toggle(id: string) {
  expandedId.value = expandedId.value === id ? null : id;
  if (expandedId.value === id) markRead(id);
}

function getSquadForSource(source: string): Squad | undefined {
  if (!source.startsWith("squad-")) return undefined;
  const squadId = source.slice("squad-".length);
  return squads.value.find((s) => s.id === squadId);
}

const decoratedItems = computed(() =>
  items.value.map((item) => {
    const squad = getSquadForSource(item.source);
    return { ...item, squad };
  })
);

onMounted(async () => {
  await Promise.all([loadFeed(), loadSquads()]);
});
function getSourceLabel(item: FeedItem & { squad?: Squad }): string {
  return item.squad?.name ?? item.source;
}
</script>

<template>
  <div class="p-6">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold">Feed</h1>
      <div class="flex gap-2">
        <button
          v-for="f in (['all', 'unread'] as const)"
          :key="f"
          @click="filter = f; loadFeed()"
          class="px-3 py-1.5 text-xs rounded-md border transition-colors"
          :class="filter === f ? 'bg-primary text-primary-foreground border-primary' : 'border-border text-muted-foreground hover:text-foreground'"
        >
          {{ f === 'all' ? 'All' : `Unread (${unreadCount})` }}
        </button>
      </div>
    </div>

    <div v-if="loading" class="text-muted-foreground">Loading...</div>

    <div v-else-if="items.length === 0" class="text-center py-12 text-muted-foreground">
      <Inbox class="w-12 h-12 mx-auto mb-3 opacity-50" />
      <p>No feed items.</p>
    </div>

    <div v-else class="space-y-2">
      <div
        v-for="item in decoratedItems"
        :key="item.id"
        class="border border-border rounded-lg overflow-hidden"
        :class="{ 'border-l-2 border-l-primary': !item.read }"
      >
        <div
          @click="toggle(item.id)"
          class="flex items-center gap-3 px-4 py-3 cursor-pointer hover:bg-muted/50 transition-colors"
        >
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2">
              <span
                class="text-xs px-2 py-0.5 rounded-full"
                :class="{ 'bg-secondary text-secondary-foreground': !item.squad }"
                :style="item.squad ? getSquadLabelStyle(item.squad.color) : {}"
              >
                {{ getSourceLabel(item) }}
              </span>
              <span class="text-sm font-medium truncate" :class="{ 'font-bold': !item.read }">
                {{ item.title }}
              </span>
            </div>
            <p class="text-xs text-muted-foreground mt-0.5">{{ item.created_at }}</p>
          </div>
          <div class="flex gap-1">
            <button
              v-if="!item.read"
              @click.stop="markRead(item.id)"
              class="p-1.5 rounded hover:bg-accent text-muted-foreground"
              title="Mark as read"
            >
              <Check class="w-3.5 h-3.5" />
            </button>
            <button
              @click.stop="deleteItem(item.id)"
              class="p-1.5 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive"
              title="Delete"
            >
              <Trash2 class="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
        <div v-if="expandedId === item.id" class="px-4 pb-3 border-t border-border pt-3">
          <MarkdownContent :content="item.content" />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/web/src/views/FeedView.tsx
import { api } from '@/lib/api';
import { Inbox } from 'lucide-react';
import { marked } from 'marked';
import { useEffect, useState } from 'react';

interface FeedItem {
	id: string;
	kind: string;
	title: string;
	content: string;
	squadId: string | null;
	status: string;
	response: string | null;
	createdAt: string;
}

export function FeedView() {
	const [items, setItems] = useState<FeedItem[]>([]);
	const [selected, setSelected] = useState<FeedItem | null>(null);

	useEffect(() => {
		api
			.get<{ entries: FeedItem[] }>('/inbox')
			.then((d) => setItems(d.entries))
			.catch(() => {});
	}, []);

	function handleSelect(item: FeedItem) {
		setSelected(item);
		if (item.status === 'unread') {
			api
				.post(`/inbox/${item.id}/read`)
				.then(() => {
					setItems((prev) => prev.map((i) => (i.id === item.id ? { ...i, status: 'read' } : i)));
				})
				.catch(() => {});
		}
	}

	return (
		<div className="flex h-full">
			{/* List */}
			<div className="w-80 border-r border-[var(--color-border)] flex flex-col h-full">
				<header className="h-14 flex items-center px-4 border-b border-[var(--color-border)] shrink-0">
					<h1 className="text-lg font-semibold gradient-text">Feed</h1>
				</header>
				<div className="flex-1 overflow-y-auto">
					{items.map((item) => (
						<button
							key={item.id}
							onClick={() => handleSelect(item)}
							type="button"
							className={`w-full text-left px-4 py-3 border-b border-[var(--color-border)] hover:bg-white/3 transition-colors ${
								selected?.id === item.id ? 'bg-white/5' : ''
							}`}
						>
							<div className="flex items-center gap-2">
								{item.status === 'unread' && (
									<span className="w-2 h-2 rounded-full bg-[var(--color-accent)] shrink-0" />
								)}
								<span className="text-xs text-[var(--color-muted-foreground)] uppercase">
									{item.kind}
								</span>
							</div>
							<p className="text-sm font-medium mt-1 truncate">{item.title}</p>
							<p className="text-xs text-[var(--color-muted-foreground)] mt-0.5">
								{new Date(item.createdAt).toLocaleString()}
							</p>
						</button>
					))}
					{items.length === 0 && (
						<div className="flex flex-col items-center justify-center py-12 text-[var(--color-muted-foreground)]">
							<Inbox size={32} className="opacity-30 mb-2" />
							<p className="text-sm">No items yet</p>
						</div>
					)}
				</div>
			</div>

			{/* Detail */}
			<div className="flex-1 overflow-y-auto p-6">
				{selected ? (
					<div>
						<h2 className="text-xl font-semibold mb-1">{selected.title}</h2>
						<p className="text-xs text-[var(--color-muted-foreground)] mb-4">
							{selected.kind} · {new Date(selected.createdAt).toLocaleString()}
						</p>
						<div
							className="prose-io"
							// biome-ignore lint: markdown rendering
							dangerouslySetInnerHTML={{ __html: marked.parse(selected.content) as string }}
						/>
					</div>
				) : (
					<div className="h-full flex items-center justify-center text-[var(--color-muted-foreground)]">
						Select an item to view details
					</div>
				)}
			</div>
		</div>
	);
}
