// web/src/views/SettingsView.vue
<script setup lang="ts">
  import { ref, onMounted } from "vue";
  import { apiGet, apiPut } from "@/lib/api";

  const loading = ref(true);
  const saving = ref(false);
  const saved = ref(false);
  const activeTab = ref("general");

  const tabs = [
    { id: "general", label: "General" },
    { id: "telegram", label: "Telegram" },
    { id: "auth", label: "Auth" },
    { id: "advanced", label: "Advanced" },
  ];

  const settings = ref({
    defaultModel: "",
    port: 3170,
    telegramEnabled: false,
    telegramBotToken: "",
    authorizedUserId: null as number | null,
    supabaseUrl: "",
    supabaseAnonKey: "",
    authorizedEmail: "",
    backgroundNotifyMode: "meaningful",
    backgroundNotifyTelegram: true,
    selfEditEnabled: false,
    watchdogEnabled: true,
  });

  async function fetchSettings() {
    loading.value = true;
    try {
      const data = await apiGet("/settings");
      settings.value = data;
    } finally {
      loading.value = false;
    }
  }

  async function saveSettings() {
    saving.value = true;
    saved.value = false;
    try {
      await apiPut("/settings", settings.value);
      saved.value = true;
      setTimeout(() => (saved.value = false), 2000);
    } finally {
      saving.value = false;
    }
  }

  onMounted(fetchSettings);
</script>

<template>
  <div class="p-6">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold">Settings</h1>
      <button
        @click="saveSettings"
        :disabled="saving"
        class="px-4 py-2 rounded-md bg-primary text-primary-foreground text-sm hover:bg-primary/90 disabled:opacity-50"
      >
        {{ saving ? "Saving..." : saved ? "Saved ✓" : "Save" }}
      </button>
    </div>

    <div v-if="loading" class="text-muted-foreground">Loading...</div>

    <template v-else>
      <!-- Tabs -->
      <div class="flex gap-1 border-b border-border mb-6">
        <button
          v-for="tab in tabs"
          :key="tab.id"
          @click="activeTab = tab.id"
          class="px-4 py-2 text-sm font-medium border-b-2 transition-colors"
          :class="
            activeTab === tab.id
              ? 'border-primary text-foreground'
              : 'border-transparent text-muted-foreground hover:text-foreground'
          "
        >
          {{ tab.label }}
        </button>
      </div>

      <!-- General -->
      <div v-if="activeTab === 'general'" class="space-y-4 max-w-lg">
        <div>
          <label class="text-sm font-medium">Default Model</label>
          <input
            v-model="settings.defaultModel"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          />
        </div>
        <div>
          <label class="text-sm font-medium">Port</label>
          <input
            v-model.number="settings.port"
            type="number"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          />
          <p class="text-xs text-muted-foreground mt-1">Requires restart to take effect</p>
        </div>
        <div>
          <label class="text-sm font-medium">Background Notify Mode</label>
          <select
            v-model="settings.backgroundNotifyMode"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          >
            <option value="all">All</option>
            <option value="meaningful">Meaningful</option>
            <option value="off">Off</option>
          </select>
        </div>
        <div class="flex items-center gap-3">
          <input
            v-model="settings.backgroundNotifyTelegram"
            type="checkbox"
            id="notifyTelegram"
            class="rounded"
          />
          <label for="notifyTelegram" class="text-sm font-medium"
            >Send notifications via Telegram</label
          >
        </div>
      </div>

      <!-- Telegram -->
      <div v-if="activeTab === 'telegram'" class="space-y-4 max-w-lg">
        <div>
          <label class="text-sm font-medium">Bot Token</label>
          <input
            v-model="settings.telegramBotToken"
            type="password"
            placeholder="Enter new token to update"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          />
        </div>
        <div>
          <label class="text-sm font-medium">Authorized User ID</label>
          <input
            v-model.number="settings.authorizedUserId"
            type="number"
            placeholder="123456789"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          />
        </div>
        <div class="flex items-center gap-3">
          <input
            v-model="settings.telegramEnabled"
            type="checkbox"
            id="telegramEnabled"
            class="rounded"
          />
          <label for="telegramEnabled" class="text-sm font-medium">Enable Telegram Bot</label>
        </div>
      </div>

      <!-- Auth -->
      <div v-if="activeTab === 'auth'" class="space-y-4 max-w-lg">
        <div>
          <label class="text-sm font-medium">Supabase URL</label>
          <input
            v-model="settings.supabaseUrl"
            placeholder="https://your-project.supabase.co"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          />
        </div>
        <div>
          <label class="text-sm font-medium">Supabase Anon Key</label>
          <input
            v-model="settings.supabaseAnonKey"
            type="password"
            placeholder="Enter new key to update"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          />
        </div>
        <div>
          <label class="text-sm font-medium">Authorized Email</label>
          <input
            v-model="settings.authorizedEmail"
            type="email"
            placeholder="you@example.com"
            class="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
          />
        </div>
      </div>

      <!-- Advanced -->
      <div v-if="activeTab === 'advanced'" class="space-y-4 max-w-lg">
        <div class="flex items-center gap-3">
          <input v-model="settings.selfEditEnabled" type="checkbox" id="selfEdit" class="rounded" />
          <div>
            <label for="selfEdit" class="text-sm font-medium">Self-Edit Mode</label>
            <p class="text-xs text-muted-foreground">Allow IO to modify its own source code</p>
          </div>
        </div>
        <div class="flex items-center gap-3">
          <input v-model="settings.watchdogEnabled" type="checkbox" id="watchdog" class="rounded" />
          <div>
            <label for="watchdog" class="text-sm font-medium">Watchdog</label>
            <p class="text-xs text-muted-foreground">Monitor event loop and zombie instances</p>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

// packages/web/src/views/SettingsView.tsx
import { useEffect, useState } from "react";
import { Save } from "lucide-react";
import { api } from "@/lib/api";
import { toast } from "sonner";

interface Config {
	apiPort: number;
	logLevel: string;
	defaultModel: string;
	maxInstancesPerSquad: number;
	dataDir: string;
	pricing: { refreshIntervalHours: number };
	telegram: { botToken: string | null; allowedChatIds: number[] };
	supabase: { projectUrl: string | null; anonKey: string | null };
}

type TabId = "general" | "telegram" | "auth" | "models" | "advanced";

export function SettingsView() {
	const [config, setConfig] = useState<Config | null>(null);
	const [tab, setTab] = useState<TabId>("general");
	const [dirty, setDirty] = useState(false);

	useEffect(() => {
		api.get<{ config: Config }>("/config").then((d) => setConfig(d.config)).catch(() => {});
	}, []);

	function update(patch: Partial<Config>) {
		if (!config) return;
		setConfig({ ...config, ...patch });
		setDirty(true);
	}

	async function save() {
		if (!config) return;
		try {
			const { dataDir: _, ...rest } = config;
			await api.patch("/config", rest);
			toast.success("Settings saved");
			setDirty(false);
		} catch {
			toast.error("Failed to save settings");
		}
	}

	if (!config) {
		return (
			<div className="h-full flex items-center justify-center text-[var(--color-muted-foreground)]">
				Loading...
			</div>
		);
	}

	const TABS: { id: TabId; label: string }[] = [
		{ id: "general", label: "General" },
		{ id: "telegram", label: "Telegram" },
		{ id: "auth", label: "Auth" },
		{ id: "models", label: "Models" },
		{ id: "advanced", label: "Advanced" },
	];

	return (
		<div className="h-full overflow-y-auto p-6">
			<header className="flex items-center justify-between mb-6">
				<div>
					<h1 className="text-2xl font-bold gradient-text">Settings</h1>
					<p className="text-sm text-[var(--color-muted-foreground)] mt-1">
						Configure IO daemon behavior
					</p>
				</div>
				{dirty && (
					<button
						type="button"
						onClick={save}
						className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[var(--color-accent)] text-white text-sm hover:opacity-90"
					>
						<Save size={16} /> Save Changes
					</button>
				)}
			</header>

			{/* Tabs */}
			<div className="flex gap-1 mb-6 p-1 rounded-lg bg-white/3 w-fit">
				{TABS.map((t) => (
					<button
						key={t.id}
						type="button"
						onClick={() => setTab(t.id)}
						className={`px-4 py-1.5 rounded-md text-sm font-medium transition-colors ${
							tab === t.id ? "bg-white/10 text-[var(--color-foreground)]" : "text-[var(--color-muted-foreground)]"
						}`}
					>
						{t.label}
					</button>
				))}
			</div>

			{/* Content */}
			<div className="glass-card p-6 max-w-2xl">
				{tab === "general" && (
					<div className="space-y-4">
						<Field label="Log Level">
							<select
								value={config.logLevel}
								onChange={(e) => update({ logLevel: e.target.value })}
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none"
							>
								{["trace", "debug", "info", "warn", "error", "fatal"].map((l) => (
									<option key={l} value={l}>{l}</option>
								))}
							</select>
						</Field>
						<Field label="Default Model">
							<input
								type="text"
								value={config.defaultModel}
								onChange={(e) => update({ defaultModel: e.target.value })}
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
							/>
						</Field>
						<Field label="Max Instances Per Squad">
							<input
								type="number"
								value={config.maxInstancesPerSquad}
								onChange={(e) => update({ maxInstancesPerSquad: Number(e.target.value) })}
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
								min={1}
								max={10}
							/>
						</Field>
						<Field label="API Port">
							<input
								type="number"
								value={config.apiPort}
								onChange={(e) => update({ apiPort: Number(e.target.value) })}
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
							/>
						</Field>
					</div>
				)}

				{tab === "telegram" && (
					<div className="space-y-4">
						<Field label="Bot Token">
							<input
								type="password"
								value={config.telegram.botToken ?? ""}
								onChange={(e) =>
									update({ telegram: { ...config.telegram, botToken: e.target.value || null } })
								}
								placeholder="Enter Telegram bot token"
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
							/>
						</Field>
						<Field label="Allowed Chat IDs (comma-separated)">
							<input
								type="text"
								value={config.telegram.allowedChatIds.join(", ")}
								onChange={(e) =>
									update({
										telegram: {
											...config.telegram,
											allowedChatIds: e.target.value
												.split(",")
												.map((s) => Number(s.trim()))
												.filter((n) => !Number.isNaN(n)),
										},
									})
								}
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)] font-mono"
							/>
						</Field>
					</div>
				)}

				{tab === "auth" && (
					<div className="space-y-4">
						<Field label="Supabase Project URL">
							<input
								type="text"
								value={config.supabase.projectUrl ?? ""}
								onChange={(e) =>
									update({ supabase: { ...config.supabase, projectUrl: e.target.value || null } })
								}
								placeholder="https://your-project.supabase.co"
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)] font-mono"
							/>
						</Field>
						<Field label="Supabase Anon Key">
							<input
								type="password"
								value={config.supabase.anonKey ?? ""}
								onChange={(e) =>
									update({ supabase: { ...config.supabase, anonKey: e.target.value || null } })
								}
								placeholder="eyJhbGciOiJIUzI1NiIs..."
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)] font-mono"
							/>
						</Field>
						<p className="text-xs text-[var(--color-muted-foreground)]">
							When configured, the web dashboard requires Supabase authentication to access.
							Find these values in your Supabase project settings → API.
						</p>
					</div>
				)}

				{tab === "models" && (
					<div className="space-y-4">
						<Field label="Pricing Refresh Interval (hours)">
							<input
								type="number"
								value={config.pricing.refreshIntervalHours}
								onChange={(e) =>
									update({ pricing: { refreshIntervalHours: Number(e.target.value) } })
								}
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none focus:border-[var(--color-accent)]"
								min={1}
							/>
						</Field>
						<p className="text-xs text-[var(--color-muted-foreground)]">
							Model pricing is auto-refreshed from GitHub docs at this interval.
						</p>
					</div>
				)}

				{tab === "advanced" && (
					<div className="space-y-4">
						<Field label="Data Directory">
							<input
								type="text"
								value={config.dataDir}
								disabled
								className="w-full px-3 py-2 rounded-md bg-[var(--color-input)] border border-[var(--color-border)] text-sm outline-none opacity-60 cursor-not-allowed font-mono"
							/>
							<p className="text-xs text-[var(--color-muted-foreground)] mt-1">
								Cannot be changed while daemon is running.
							</p>
						</Field>
					</div>
				)}
			</div>
		</div>
	);
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
	return (
		<div>
			<label className="block text-sm font-medium text-[var(--color-foreground)] mb-1.5">
				{label}
			</label>
			{children}
		</div>
	);
}
