// web/src/components/AppSidebar.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { useRoute } from "vue-router";
import LogoIcon from "@/components/LogoIcon.vue";
import {
  MessageSquare,
  Users,
  Activity,
  Inbox,
  Puzzle,
  Server,
  Clock,
  BookOpen,
  History,
  Settings,
  BarChart3,
  ClipboardList,
  PanelLeftClose,
  PanelLeftOpen,
  Github,
} from "lucide-vue-next";

const route = useRoute();

const collapsed = ref(false);

const navItems = [
  { name: "History", icon: History, path: "/history" },
  { name: "Squads", icon: Users, path: "/squads" },
  { name: "Health", icon: Activity, path: "/squads/health" },
  { name: "Usage", icon: BarChart3, path: "/usage" },
  { name: "Audit Log", icon: ClipboardList, path: "/audit-log" },
  { name: "Skills", icon: Puzzle, path: "/skills" },
  { name: "MCP Servers", icon: Server, path: "/mcp" },
  { name: "Schedules", icon: Clock, path: "/schedules" },
  { name: "Wiki", icon: BookOpen, path: "/wiki" },
];

const footerItems = [
  { name: "Chat", icon: MessageSquare, path: "/" },
  { name: "Feed", icon: Inbox, path: "/feed" },
  { name: "Settings", icon: Settings, path: "/settings" },
];

const APP_VERSION = __APP_VERSION__;
const REPO_URL = "https://github.com/michaeljolley/io";

// Find the best (longest prefix) matching nav path for the current route.
const activeNavPath = computed(() => {
  let bestPath = "";
  const allItems = [...navItems, ...footerItems];
  for (const item of allItems) {
    const p = item.path;
    const matches =
      p === "/"
        ? route.path === "/"
        : route.path === p || route.path.startsWith(p + "/");
    if (matches && p.length > bestPath.length) {
      bestPath = p;
    }
  }
  return bestPath;
});

function toggleCollapse() {
  collapsed.value = !collapsed.value;
}
</script>

<template>
  <aside
    :class="[
      'border-r border-border bg-sidebar flex flex-col h-full shrink-0 transition-all duration-200',
      collapsed ? 'w-16' : 'w-56',
    ]"
  >
    <!-- Logo + Collapse toggle -->
    <div class="p-3 border-b border-border flex items-center" :class="collapsed ? 'justify-center' : 'justify-between'">
      <router-link to="/" class="flex items-center gap-2" :class="collapsed ? 'justify-center' : ''">
        <LogoIcon :size="24" />
        <h1 v-if="!collapsed" class="font-display text-[1.1rem] font-normal uppercase tracking-[0.18em] bg-gradient-brand bg-clip-text text-transparent">IO</h1>
      </router-link>
      <button
        @click="toggleCollapse"
        class="p-1 rounded-full hover:bg-accent/70 text-muted-foreground hover:text-foreground transition-colors"
        :title="collapsed ? 'Expand sidebar' : 'Collapse sidebar'"
        v-if="!collapsed"
      >
        <PanelLeftClose class="w-4 h-4" />
      </button>
    </div>

    <!-- Expand button when collapsed -->
    <button
      v-if="collapsed"
      @click="toggleCollapse"
      class="mx-auto mt-2 p-1.5 rounded-full hover:bg-accent/70 text-muted-foreground hover:text-foreground transition-colors"
      title="Expand sidebar"
    >
      <PanelLeftOpen class="w-4 h-4" />
    </button>

    <!-- Navigation -->
    <nav class="flex-1 p-2 space-y-0.5 overflow-y-auto">
      <router-link
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        class="flex items-center gap-3 rounded-full text-sm transition-colors border border-transparent"
        :class="[
          collapsed ? 'justify-center px-2 py-2' : 'px-3 py-2',
          activeNavPath === item.path
            ? 'bg-accent text-accent-foreground font-medium border border-white/10'
            : 'text-muted-foreground hover:bg-white/5 hover:text-foreground',
        ]"
        :title="collapsed ? item.name : undefined"
      >
        <component :is="item.icon" class="w-4 h-4 shrink-0" />
        <span v-if="!collapsed">{{ item.name }}</span>
      </router-link>
    </nav>

    <!-- Footer -->
    <div class="border-t border-border p-2 space-y-0.5">
      <router-link
        v-for="item in footerItems"
        :key="item.path"
        :to="item.path"
        class="flex items-center gap-3 rounded-full text-sm transition-colors border border-transparent"
        :class="[
          collapsed ? 'justify-center px-2 py-2' : 'px-3 py-2',
          activeNavPath === item.path
            ? 'bg-accent text-accent-foreground font-medium border border-white/10'
            : 'text-muted-foreground hover:bg-white/5 hover:text-foreground',
        ]"
        :title="collapsed ? item.name : undefined"
      >
        <component :is="item.icon" class="w-4 h-4 shrink-0" />
        <span v-if="!collapsed">{{ item.name }}</span>
      </router-link>

      <!-- Version + GitHub -->
      <div
        class="flex items-center pt-2 mt-2 border-t border-border"
        :class="collapsed ? 'justify-center' : 'justify-between px-3'"
      >
        <a
          v-if="!collapsed"
          :href="`${REPO_URL}/releases/tag/v${APP_VERSION}`"
          target="_blank"
          class="text-[10px] text-muted-foreground hover:text-foreground transition-colors"
          title="Release notes"
        >
          v{{ APP_VERSION }}
        </a>
        <a
          :href="REPO_URL"
          target="_blank"
          class="p-1 rounded-full hover:bg-accent/70 text-muted-foreground hover:text-foreground transition-colors"
          title="GitHub repository"
        >
          <Github class="w-3.5 h-3.5" />
        </a>
      </div>
    </div>
  </aside>
</template>

// web/src/components/AppSidebar.tsx
import {
  BarChart2,
  BookOpen,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Inbox,
  MessageSquare,
  Settings,
  Users,
  Zap,
} from "lucide-react";
import { useState } from "react";
import { useLocation, useNavigate } from "react-router";
import { IoMark } from "./IoMark";

type NavItem = { path: string; icon: React.ElementType; label: string };

const NAV_TOP: NavItem[] = [
  { path: "/squads", icon: Users, label: "Squads" },
  { path: "/skills", icon: Zap, label: "Skills" },
  { path: "/schedules", icon: Calendar, label: "Schedules" },
  { path: "/wiki", icon: BookOpen, label: "Wiki" },
  { path: "/usage", icon: BarChart2, label: "Usage" },
];

const NAV_BOTTOM: NavItem[] = [
  { path: "/chat", icon: MessageSquare, label: "Chat" },
  { path: "/feed", icon: Inbox, label: "Inbox" },
  { path: "/settings", icon: Settings, label: "Settings" },
];

function NavBtn({
  item,
  active,
  collapsed,
  onClick,
}: {
  item: NavItem;
  active: boolean;
  collapsed: boolean;
  onClick: () => void;
}) {
  const Icon = item.icon;
  return (
    <button
      onClick={onClick}
      title={collapsed ? item.label : undefined}
      className={`w-full flex items-center cursor-pointer gap-2.5 px-2 py-2 rounded-xl text-[11px] font-mono transition-colors ${active ? "text-[#66FCF1]" : "text-zinc-600 hover:text-zinc-300 hover:bg-white/[0.04]"} ${collapsed ? "justify-center" : ""}`}
      style={active ? { background: "rgba(102,252,241,0.1)" } : undefined}
    >
      <Icon className="w-3.5 h-3.5 flex-shrink-0" />
      {!collapsed && item.label}
    </button>
  );
}

export function AppSidebar() {
  const [collapsed, setCollapsed] = useState(false);
  const location = useLocation();
  const navigate = useNavigate();

  const isActive = (path: string) => {
    if (path === "/squads") return location.pathname.startsWith("/squads");
    if (path === "/chat") return location.pathname === "/" || location.pathname === "/chat";
    return location.pathname === path;
  };

  return (
    <div
      className={`flex-shrink-0 flex flex-col border-r border-white/[0.06] bg-[#181818] transition-all duration-200 ${collapsed ? "w-[52px]" : "w-[210px]"}`}
    >
      {/* Logo header */}
      <div
        className={`h-[52px] flex items-center border-b border-white/[0.06] flex-shrink-0 ${collapsed ? "justify-center px-3" : "justify-between pl-4 pr-3"}`}
      >
        {collapsed ? (
          <IoMark height={26} />
        ) : (
          <div className="flex items-center gap-2.5">
            <IoMark height={26} />
            <span
              className="text-2xl text-white tracking-wider leading-none"
              style={{ fontFamily: "'Bebas Neue', sans-serif" }}
            >
              IO
            </span>
          </div>
        )}
      </div>

      {/* Top nav */}
      <nav className="flex-1 py-2 px-1.5 space-y-0.5 overflow-y-auto">
        {NAV_TOP.map((item) => (
          <NavBtn
            key={item.path}
            item={item}
            active={isActive(item.path)}
            collapsed={collapsed}
            onClick={() => navigate(item.path)}
          />
        ))}
      </nav>

      {/* Bottom nav */}
      <div className="flex-shrink-0 border-t border-white/[0.06]">
        <div className="py-1.5 px-1.5 space-y-0.5">
          {NAV_BOTTOM.map((item) => (
            <NavBtn
              key={item.path}
              item={item}
              active={isActive(item.path)}
              collapsed={collapsed}
              onClick={() => navigate(item.path)}
            />
          ))}
        </div>
        <div className="border-t border-white/[0.05] py-1.5 px-1.5 space-y-0.5">
          <a
            href="https://github.com/michaeljolley/io"
            target="_blank"
            rel="noopener noreferrer"
            title="GitHub"
            className={`flex items-center gap-2.5 px-2 py-2 rounded-xl text-[11px] font-mono text-zinc-600 hover:text-zinc-300 hover:bg-white/[0.04] transition-colors ${collapsed ? "justify-center" : ""}`}
          >
            <svg className="w-3.5 h-3.5 flex-shrink-0" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
            </svg>
            {!collapsed && <span className="text-zinc-700">v0.9.2</span>}
          </a>
          <button
            onClick={() => setCollapsed(!collapsed)}
            title={collapsed ? "Expand sidebar" : "Collapse sidebar"}
            className={`w-full flex items-center gap-2.5 px-2 py-2 rounded-xl text-[11px] font-mono text-zinc-600 hover:text-zinc-300 hover:bg-white/[0.04] transition-colors ${collapsed ? "justify-center" : ""}`}
          >
            {collapsed ? (
              <ChevronRight className="w-3.5 h-3.5 flex-shrink-0" />
            ) : (
              <ChevronLeft className="w-3.5 h-3.5 flex-shrink-0" />
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
